unit Printers;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls
type
  TPrinterCanvas=class(TForm)
    Printer: N.A.;
    procedure CreateHandle(Sender : TObject);
    procedure Changing(Sender : TObject);
    procedure UpdateFont(TPrinterCanvas);(Sender : TObject);
    procedure _PROC_0042F5BC(Sender : TObject);
    procedure _PROC_0042F5F8(Sender : TObject);
    procedure _PROC_0042F674(Sender : TObject);
    procedure _PROC_0042F7A0(Sender : TObject);
    procedure _PROC_0042F810(Sender : TObject);
    procedure _PROC_0042F898(Sender : TObject);
    procedure _PROC_0042F8CC(Sender : TObject);
    procedure _PROC_0042F8FC(Sender : TObject);
    procedure _PROC_0042F939(Sender : TObject);
    procedure _PROC_0042FB80(Sender : TObject);
    procedure _PROC_0042FBA0(Sender : TObject);
    procedure _PROC_0042FBB4(Sender : TObject);
    procedure _PROC_0042FBD0(Sender : TObject);
    procedure _PROC_0042FBEC(Sender : TObject);
    procedure _PROC_0042FC04(Sender : TObject);
    procedure _PROC_0042FE44(Sender : TObject);
    procedure _PROC_00430081(Sender : TObject);
    procedure _PROC_004300AC(Sender : TObject);
    procedure _PROC_004300E8(Sender : TObject);
    procedure _PROC_004300F0(Sender : TObject);
    procedure _PROC_00430124(Sender : TObject);
    procedure _PROC_0043014C(Sender : TObject);
    procedure _PROC_004302D5(Sender : TObject);
    procedure _PROC_004303D1(Sender : TObject);
    procedure _PROC_00430400(Sender : TObject);
    procedure _PROC_00430410(Sender : TObject);
    procedure _PROC_0042F4F4(Sender : TObject);
    procedure _PROC_0043008C(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end ;

var
  PrinterCanvas: TPrinterCanvas;

{This file is generated by DeDe Ver 3.50.04 Copyright (c) 1999-2002 DaFixer}

implementation

{$R *.DFM}

procedure TPrinterCanvas.CreateHandle(Sender : TObject);
begin
(*
0042F530   53                     push    ebx
0042F531   8BD8                   mov     ebx, eax
0042F533   B201                   mov     dl, $01
0042F535   8B4358                 mov     eax, [ebx+$58]

* Reference to: Printers.TPrinter.SetState(TPrinter;TPrinterState);
|
0042F538   E837010000             call    0042F674
0042F53D   8BC3                   mov     eax, ebx

* Reference to: Printers.TPrinterCanvas.UpdateFont(TPrinterCanvas);
|
0042F53F   E830000000             call    0042F574
0042F544   8B4358                 mov     eax, [ebx+$58]
0042F547   8B5020                 mov     edx, [eax+$20]
0042F54A   8BC3                   mov     eax, ebx

* Reference to: Graphics.TCanvas.SetHandle(TCanvas;HDC);
|
0042F54C   E83F73FFFF             call    00426890
0042F551   5B                     pop     ebx
0042F552   C3                     ret

*)
end;

procedure TPrinterCanvas.Changing(Sender : TObject);
begin
(*
0042F554   53                     push    ebx
0042F555   8BD8                   mov     ebx, eax
0042F557   B201                   mov     dl, $01
0042F559   8B4358                 mov     eax, [ebx+$58]

* Reference to: Printers.TPrinter.CheckPrinting(TPrinter;Boolean);
|
0042F55C   E83F020000             call    0042F7A0
0042F561   8BC3                   mov     eax, ebx

* Reference to: DdeMan.TDdeServerConv.Connect(TDdeServerConv);
|
0042F563   E8F073FFFF             call    00426958
0042F568   8BC3                   mov     eax, ebx

* Reference to: Printers.TPrinterCanvas.UpdateFont(TPrinterCanvas);
|
0042F56A   E805000000             call    0042F574
0042F56F   5B                     pop     ebx
0042F570   C3                     ret

*)
end;

procedure TPrinterCanvas.UpdateFont(TPrinterCanvas);(Sender : TObject);
begin
(*
0042F574   53                     push    ebx
0042F575   56                     push    esi
0042F576   57                     push    edi
0042F577   8BD8                   mov     ebx, eax
0042F579   6A5A                   push    $5A
0042F57B   8B4358                 mov     eax, [ebx+$58]
0042F57E   8B4020                 mov     eax, [eax+$20]
0042F581   50                     push    eax

* Reference to: InitCommonControls.GetDeviceCaps()
|
0042F582   E85175FDFF             call    00406AD8

* Reference to field TPrinterCanvas.OFFS_000C
|
0042F587   8B730C                 mov     esi, [ebx+$0C]
0042F58A   3B461C                 cmp     eax, [esi+$1C]
0042F58D   7426                   jz      0042F5B5
0042F58F   8BC6                   mov     eax, esi

* Reference to: Graphics.TFont.GetSize(TFont):Integer;
|
0042F591   E8C664FFFF             call    00425A5C
0042F596   8BF0                   mov     esi, eax
0042F598   6A5A                   push    $5A
0042F59A   8B4358                 mov     eax, [ebx+$58]
0042F59D   8B4020                 mov     eax, [eax+$20]
0042F5A0   50                     push    eax

* Reference to: InitCommonControls.GetDeviceCaps()
|
0042F5A1   E83275FDFF             call    00406AD8

* Reference to field TPrinterCanvas.OFFS_000C
|
0042F5A6   8B7B0C                 mov     edi, [ebx+$0C]
0042F5A9   89471C                 mov     [edi+$1C], eax
0042F5AC   8BD6                   mov     edx, esi
0042F5AE   8BC7                   mov     eax, edi

* Reference to: Graphics.TFont.SetSize(TFont;Integer);
|
0042F5B0   E8C364FFFF             call    00425A78
0042F5B5   5F                     pop     edi
0042F5B6   5E                     pop     esi
0042F5B7   5B                     pop     ebx
0042F5B8   C3                     ret

*)
end;

procedure TPrinterCanvas._PROC_0042F5BC(Sender : TObject);
begin
(*
0042F5BC   53                     push    ebx
0042F5BD   56                     push    esi
0042F5BE   84D2                   test    dl, dl
0042F5C0   7408                   jz      0042F5CA
0042F5C2   83C4F0                 add     esp, -$10

* Reference to: System.@ClassCreate(TClass;Boolean):TObject;
|
0042F5C5   E88241FDFF             call    0040374C
0042F5CA   8BDA                   mov     ebx, edx
0042F5CC   8BF0                   mov     esi, eax
0042F5CE   33D2                   xor     edx, edx
0042F5D0   8BC6                   mov     eax, esi

* Reference to: InStack.TInStack.Create(TInStack;boolean);
|
0042F5D2   E8E13DFDFF             call    004033B8

* Reference to field TPrinterCanvas.OFFS_0014
|
0042F5D7   C74614FFFFFFFF         mov     dword ptr [esi+$14], $FFFFFFFF
0042F5DE   8BC6                   mov     eax, esi
0042F5E0   84DB                   test    bl, bl
0042F5E2   740F                   jz      0042F5F3

* Reference to: System.@AfterConstruction(TObject):TObject;
|
0042F5E4   E8BB41FDFF             call    004037A4
0042F5E9   648F0500000000         pop     dword ptr fs:[$00000000]
0042F5F0   83C40C                 add     esp, +$0C
0042F5F3   8BC6                   mov     eax, esi
0042F5F5   5E                     pop     esi
0042F5F6   5B                     pop     ebx
0042F5F7   C3                     ret

*)
end;

procedure TPrinterCanvas._PROC_0042F5F8(Sender : TObject);
begin
(*
0042F5F8   53                     push    ebx
0042F5F9   56                     push    esi

* Reference to: System.@BeforeDestruction(TObject;Shortint):TObject;
|
0042F5FA   E8B541FDFF             call    004037B4
0042F5FF   8BDA                   mov     ebx, edx
0042F601   8BF0                   mov     esi, eax

* Reference to field TPrinterCanvas.OFFS_001C
|
0042F603   807E1C00               cmp     byte ptr [esi+$1C], $00
0042F607   7407                   jz      0042F610
0042F609   8BC6                   mov     eax, esi

* Reference to: Printers.TPrinter.EndDoc(TPrinter);
|
0042F60B   E888020000             call    0042F898
0042F610   33D2                   xor     edx, edx
0042F612   8BC6                   mov     eax, esi

* Reference to: Printers.TPrinter.SetState(TPrinter;TPrinterState);
|
0042F614   E85B000000             call    0042F674
0042F619   8BC6                   mov     eax, esi

* Reference to: Printers.TPrinter.FreePrinters(TPrinter);
|
0042F61B   E8240A0000             call    00430044
0042F620   8BC6                   mov     eax, esi

* Reference to: Printers.TPrinter.FreeFonts(TPrinter);
|
0042F622   E8590A0000             call    00430080

* Reference to field TPrinterCanvas.OFFS_0004
|
0042F627   8B4604                 mov     eax, [esi+$04]

* Reference to: System.TObject.Free(TObject);
|
0042F62A   E8B93DFDFF             call    004033E8

* Reference to field TPrinterCanvas.OFFS_002C
|
0042F62F   8B462C                 mov     eax, [esi+$2C]
0042F632   85C0                   test    eax, eax
0042F634   7406                   jz      0042F63C
0042F636   50                     push    eax

* Reference to: GetFileVersionInfoA.ClosePrinter()
|
0042F637   E8DCFAFFFF             call    0042F118

* Reference to field TPrinterCanvas.OFFS_0028
|
0042F63C   8B4628                 mov     eax, [esi+$28]
0042F63F   85C0                   test    eax, eax
0042F641   7414                   jz      0042F657
0042F643   50                     push    eax

* Reference to: GetModuleHandleA.GlobalUnlock()
|
0042F644   E8A772FDFF             call    004068F0

* Reference to field TPrinterCanvas.OFFS_0028
|
0042F649   8B4628                 mov     eax, [esi+$28]
0042F64C   50                     push    eax

* Reference to: GetModuleHandleA.GlobalFree()
|
0042F64D   E87672FDFF             call    004068C8
0042F652   33C0                   xor     eax, eax

* Reference to field TPrinterCanvas.OFFS_0028
|
0042F654   894628                 mov     [esi+$28], eax
0042F657   8BD3                   mov     edx, ebx
0042F659   80E2FC                 and     dl, $FC
0042F65C   8BC6                   mov     eax, esi

* Reference to: System.TObject.Destroy(TObject;Boolean);
|
0042F65E   E8753DFDFF             call    004033D8
0042F663   84DB                   test    bl, bl
0042F665   7E07                   jle     0042F66E
0042F667   8BC6                   mov     eax, esi

* Reference to: System.@ClassDestroy(TObject);
|
0042F669   E82E41FDFF             call    0040379C
0042F66E   5E                     pop     esi
0042F66F   5B                     pop     ebx
0042F670   C3                     ret

*)
end;

procedure TPrinterCanvas._PROC_0042F674(Sender : TObject);
begin
(*
0042F674   55                     push    ebp
0042F675   8BEC                   mov     ebp, esp
0042F677   83C4F8                 add     esp, -$08
0042F67A   53                     push    ebx
0042F67B   56                     push    esi
0042F67C   57                     push    edi
0042F67D   33C9                   xor     ecx, ecx
0042F67F   894DF8                 mov     [ebp-$08], ecx
0042F682   8BDA                   mov     ebx, edx
0042F684   8BF0                   mov     esi, eax
0042F686   33C0                   xor     eax, eax
0042F688   55                     push    ebp

* Possible String Reference to: 'ÈÂC˝ˇÎ_^[YY]√UãÏj'
|
0042F689   6892F74200             push    $0042F792

***** TRY
|
0042F68E   64FF30                 push    dword ptr fs:[eax]
0042F691   648920                 mov     fs:[eax], esp

* Reference to field TPrinterCanvas.OFFS_001F
|
0042F694   8A461F                 mov     al, byte ptr [esi+$1F]
0042F697   3AD8                   cmp     bl, al
0042F699   0F84DD000000           jz      0042F77C
0042F69F   33FF                   xor     edi, edi
0042F6A1   8BD3                   mov     edx, ebx
0042F6A3   80EA01                 sub     dl, $01
0042F6A6   7208                   jb      0042F6B0
0042F6A8   742D                   jz      0042F6D7
0042F6AA   FECA                   dec     dl
0042F6AC   7438                   jz      0042F6E6
0042F6AE   EB56                   jmp     0042F706
0042F6B0   33D2                   xor     edx, edx
0042F6B2   8BC6                   mov     eax, esi

* Reference to: Printers.TPrinter.CheckPrinting(TPrinter;Boolean);
|
0042F6B4   E8E7000000             call    0042F7A0

* Reference to field TPrinterCanvas.OFFS_0004
|
0042F6B9   8B4604                 mov     eax, [esi+$04]
0042F6BC   85C0                   test    eax, eax
0042F6BE   7407                   jz      0042F6C7
0042F6C0   33D2                   xor     edx, edx

* Reference to: Graphics.TCanvas.SetHandle(TCanvas;HDC);
|
0042F6C2   E8C971FFFF             call    00426890

* Reference to field TPrinterCanvas.OFFS_0020
|
0042F6C7   8B4620                 mov     eax, [esi+$20]
0042F6CA   50                     push    eax

* Reference to: InitCommonControls.DeleteDC()
|
0042F6CB   E89073FDFF             call    00406A60
0042F6D0   33C0                   xor     eax, eax

* Reference to field TPrinterCanvas.OFFS_0020
|
0042F6D2   894620                 mov     [esi+$20], eax
0042F6D5   EB2F                   jmp     0042F706
0042F6D7   3C02                   cmp     al, $02
0042F6D9   0F849D000000           jz      0042F77C

* Possible String Reference to: 'ˇ%Ë$J'
|
0042F6DF   BF386A4000             mov     edi, $00406A38
0042F6E4   EB20                   jmp     0042F706

* Reference to field TPrinterCanvas.OFFS_0004
|
0042F6E6   8B4604                 mov     eax, [esi+$04]
0042F6E9   85C0                   test    eax, eax
0042F6EB   7407                   jz      0042F6F4
0042F6ED   33D2                   xor     edx, edx

* Reference to: Graphics.TCanvas.SetHandle(TCanvas;HDC);
|
0042F6EF   E89C71FFFF             call    00426890

* Reference to field TPrinterCanvas.OFFS_0020
|
0042F6F4   8B4620                 mov     eax, [esi+$20]
0042F6F7   85C0                   test    eax, eax
0042F6F9   7406                   jz      0042F701
0042F6FB   50                     push    eax

* Reference to: InitCommonControls.DeleteDC()
|
0042F6FC   E85F73FDFF             call    00406A60

* Possible String Reference to: 'ˇ%'
|
0042F701   BF086A4000             mov     edi, $00406A08
0042F706   85FF                   test    edi, edi
0042F708   746F                   jz      0042F779
0042F70A   8BC6                   mov     eax, esi

* Reference to: Printers.TPrinter.GetPrinterIndex(TPrinter):Integer;
|
0042F70C   E8DB040000             call    0042FBEC
0042F711   50                     push    eax
0042F712   8BC6                   mov     eax, esi

* Reference to: Printers.TPrinter.GetPrinters(TPrinter):TStrings;
|
0042F714   E8EB040000             call    0042FC04
0042F719   5A                     pop     edx
0042F71A   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TPrinterCanvas.OFFS_18
|
0042F71C   FF5118                 call    dword ptr [ecx+$18]
0042F71F   8945FC                 mov     [ebp-$04], eax

* Reference to field TPrinterCanvas.OFFS_0024
|
0042F722   8B4624                 mov     eax, [esi+$24]
0042F725   50                     push    eax
0042F726   8B45FC                 mov     eax, [ebp-$04]

* Reference to field TPrinterCanvas.OFFS_000C
|
0042F729   8B400C                 mov     eax, [eax+$0C]

* Reference to: System.@LStrToPChar(String):PAnsiChar;
|
0042F72C   E8074FFDFF             call    00404638
0042F731   50                     push    eax
0042F732   8B45FC                 mov     eax, [ebp-$04]

* Reference to field TPrinterCanvas.OFFS_0008
|
0042F735   8B4008                 mov     eax, [eax+$08]

* Reference to: System.@LStrToPChar(String):PAnsiChar;
|
0042F738   E8FB4EFDFF             call    00404638
0042F73D   50                     push    eax
0042F73E   8B45FC                 mov     eax, [ebp-$04]

* Reference to field TPrinterCanvas.OFFS_0004
|
0042F741   8B4004                 mov     eax, [eax+$04]

* Reference to: System.@LStrToPChar(String):PAnsiChar;
|
0042F744   E8EF4EFDFF             call    00404638
0042F749   50                     push    eax
0042F74A   FFD7                   call    edi

* Reference to field TPrinterCanvas.OFFS_0020
|
0042F74C   894620                 mov     [esi+$20], eax

* Reference to field TPrinterCanvas.OFFS_0020
|
0042F74F   837E2000               cmp     dword ptr [esi+$20], +$00
0042F753   7515                   jnz     0042F76A
0042F755   8D55F8                 lea     edx, [ebp-$08]
0042F758   A168034A00             mov     eax, dword ptr [$004A0368]

* Reference to: System.LoadResString(PResStringRec):String;
|
0042F75D   E87A6AFDFF             call    004061DC
0042F762   8B45F8                 mov     eax, [ebp-$08]

* Reference to: AxCtrls.InvalidOperation(AnsiString);
|
0042F765   E8FAFAFFFF             call    0042F264

* Reference to field TPrinterCanvas.OFFS_0004
|
0042F76A   8B4604                 mov     eax, [esi+$04]
0042F76D   85C0                   test    eax, eax
0042F76F   7408                   jz      0042F779

* Reference to field TPrinterCanvas.OFFS_0020
|
0042F771   8B5620                 mov     edx, [esi+$20]

* Reference to: Graphics.TCanvas.SetHandle(TCanvas;HDC);
|
0042F774   E81771FFFF             call    00426890

* Reference to field TPrinterCanvas.OFFS_001F
|
0042F779   885E1F                 mov     [esi+$1F], bl
0042F77C   33C0                   xor     eax, eax
0042F77E   5A                     pop     edx
0042F77F   59                     pop     ecx
0042F780   59                     pop     ecx
0042F781   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '_^[YY]√UãÏj'
|
0042F784   6899F74200             push    $0042F799
0042F789   8D45F8                 lea     eax, [ebp-$08]

* Reference to: System.@LStrClr(void;void);
|
0042F78C   E8E749FDFF             call    00404178
0042F791   C3                     ret


* Reference to: System.@HandleFinally;
|
0042F792   E9E543FDFF             jmp     00403B7C
0042F797   EBF0                   jmp     0042F789

****** END
|
0042F799   5F                     pop     edi
0042F79A   5E                     pop     esi
0042F79B   5B                     pop     ebx
0042F79C   59                     pop     ecx
0042F79D   59                     pop     ecx
0042F79E   5D                     pop     ebp
0042F79F   C3                     ret

*)
end;

procedure TPrinterCanvas._PROC_0042F7A0(Sender : TObject);
begin
(*
0042F7A0   55                     push    ebp
0042F7A1   8BEC                   mov     ebp, esp
0042F7A3   6A00                   push    $00
0042F7A5   6A00                   push    $00
0042F7A7   33C9                   xor     ecx, ecx
0042F7A9   55                     push    ebp
0042F7AA   6805F84200             push    $0042F805

***** TRY
|
0042F7AF   64FF31                 push    dword ptr fs:[ecx]
0042F7B2   648921                 mov     fs:[ecx], esp

* Reference to field TPrinterCanvas.OFFS_001C
|
0042F7B5   3A501C                 cmp     dl, byte ptr [eax+$1C]
0042F7B8   7430                   jz      0042F7EA
0042F7BA   84D2                   test    dl, dl
0042F7BC   7417                   jz      0042F7D5
0042F7BE   8D55FC                 lea     edx, [ebp-$04]
0042F7C1   A1E8034A00             mov     eax, dword ptr [$004A03E8]

* Reference to: System.LoadResString(PResStringRec):String;
|
0042F7C6   E8116AFDFF             call    004061DC
0042F7CB   8B45FC                 mov     eax, [ebp-$04]

* Reference to: AxCtrls.InvalidOperation(AnsiString);
|
0042F7CE   E891FAFFFF             call    0042F264
0042F7D3   EB15                   jmp     0042F7EA
0042F7D5   8D55F8                 lea     edx, [ebp-$08]
0042F7D8   A1EC014A00             mov     eax, dword ptr [$004A01EC]

* Reference to: System.LoadResString(PResStringRec):String;
|
0042F7DD   E8FA69FDFF             call    004061DC
0042F7E2   8B45F8                 mov     eax, [ebp-$08]

* Reference to: AxCtrls.InvalidOperation(AnsiString);
|
0042F7E5   E87AFAFFFF             call    0042F264
0042F7EA   33C0                   xor     eax, eax
0042F7EC   5A                     pop     edx
0042F7ED   59                     pop     ecx
0042F7EE   59                     pop     ecx
0042F7EF   648910                 mov     fs:[eax], edx

****** FINALLY
|
0042F7F2   680CF84200             push    $0042F80C
0042F7F7   8D45F8                 lea     eax, [ebp-$08]
0042F7FA   BA02000000             mov     edx, $00000002

* Reference to: System.@LStrArrayClr(void;void;Integer);
|
0042F7FF   E89849FDFF             call    0040419C
0042F804   C3                     ret


* Reference to: System.@HandleFinally;
|
0042F805   E97243FDFF             jmp     00403B7C
0042F80A   EBEB                   jmp     0042F7F7

****** END
|
0042F80C   59                     pop     ecx
0042F80D   59                     pop     ecx
0042F80E   5D                     pop     ebp
0042F80F   C3                     ret

*)
end;

procedure TPrinterCanvas._PROC_0042F810(Sender : TObject);
begin
(*
0042F810   53                     push    ebx
0042F811   83C4EC                 add     esp, -$14
0042F814   8BD8                   mov     ebx, eax
0042F816   33D2                   xor     edx, edx
0042F818   8BC3                   mov     eax, ebx

* Reference to: Printers.TPrinter.CheckPrinting(TPrinter;Boolean);
|
0042F81A   E881FFFFFF             call    0042F7A0
0042F81F   B202                   mov     dl, $02
0042F821   8BC3                   mov     eax, ebx

* Reference to: Printers.TPrinter.SetState(TPrinter;TPrinterState);
|
0042F823   E84CFEFFFF             call    0042F674
0042F828   8BC3                   mov     eax, ebx

* Reference to: Printers.TPrinter.GetCanvas(TPrinter):TCanvas;
|
0042F82A   E851030000             call    0042FB80

* Reference to: ActiveX.PROPSETHDR_OSVER_KIND(DWORD):Word;
|
0042F82F   E85C6CFFFF             call    00426490
0042F834   8BC3                   mov     eax, ebx

* Reference to: Printers.TPrinter.GetCanvas(TPrinter):TCanvas;
|
0042F836   E845030000             call    0042FB80

* Reference to: Printers.TPrinterCanvas.UpdateFont(TPrinterCanvas);
|
0042F83B   E834FDFFFF             call    0042F574

* Reference to field TPrinterCanvas.OFFS_001C
|
0042F840   C6431C01               mov     byte ptr [ebx+$1C], $01

* Reference to field TPrinterCanvas.OFFS_001D
|
0042F844   C6431D00               mov     byte ptr [ebx+$1D], $00

* Reference to field TPrinterCanvas.OFFS_000C
|
0042F848   C7430C01000000         mov     dword ptr [ebx+$0C], $00000001
0042F84F   8BC4                   mov     eax, esp
0042F851   33C9                   xor     ecx, ecx
0042F853   BA14000000             mov     edx, $00000014

* Reference to: System.@FillChar(void;void;Integer;Char);
|
0042F858   E84735FDFF             call    00402DA4
0042F85D   C7042414000000         mov     dword ptr [esp], $00000014

* Reference to field TPrinterCanvas.OFFS_0018
|
0042F864   8B4318                 mov     eax, [ebx+$18]

* Reference to: System.@LStrToPChar(String):PAnsiChar;
|
0042F867   E8CC4DFDFF             call    00404638
0042F86C   89442404               mov     [esp+$04], eax
0042F870   687CF24200             push    $0042F27C

* Reference to field TPrinterCanvas.OFFS_0020
|
0042F875   8B4320                 mov     eax, [ebx+$20]
0042F878   50                     push    eax

* Reference to: InitCommonControls.SetAbortProc()
|
0042F879   E86273FDFF             call    00406BE0
0042F87E   54                     push    esp

* Reference to field TPrinterCanvas.OFFS_0020
|
0042F87F   8B4320                 mov     eax, [ebx+$20]
0042F882   50                     push    eax

* Reference to: InitCommonControls.StartDocA()
|
0042F883   E8D073FDFF             call    00406C58

* Reference to field TPrinterCanvas.OFFS_0020
|
0042F888   8B4320                 mov     eax, [ebx+$20]
0042F88B   50                     push    eax

* Reference to: InitCommonControls.StartPage()
|
0042F88C   E8CF73FDFF             call    00406C60
0042F891   83C414                 add     esp, +$14
0042F894   5B                     pop     ebx
0042F895   C3                     ret

*)
end;

procedure TPrinterCanvas._PROC_0042F898(Sender : TObject);
begin
(*
0042F898   53                     push    ebx
0042F899   8BD8                   mov     ebx, eax
0042F89B   B201                   mov     dl, $01
0042F89D   8BC3                   mov     eax, ebx

* Reference to: Printers.TPrinter.CheckPrinting(TPrinter;Boolean);
|
0042F89F   E8FCFEFFFF             call    0042F7A0

* Reference to field TPrinterCanvas.OFFS_0020
|
0042F8A4   8B4320                 mov     eax, [ebx+$20]
0042F8A7   50                     push    eax

* Reference to: InitCommonControls.EndPage()
|
0042F8A8   E8D371FDFF             call    00406A80

* Reference to field TPrinterCanvas.OFFS_001D
|
0042F8AD   807B1D00               cmp     byte ptr [ebx+$1D], $00
0042F8B1   7509                   jnz     0042F8BC

* Reference to field TPrinterCanvas.OFFS_0020
|
0042F8B3   8B4320                 mov     eax, [ebx+$20]
0042F8B6   50                     push    eax

* Reference to: InitCommonControls.EndDoc()
|
0042F8B7   E8BC71FDFF             call    00406A78

* Reference to field TPrinterCanvas.OFFS_001C
|
0042F8BC   C6431C00               mov     byte ptr [ebx+$1C], $00

* Reference to field TPrinterCanvas.OFFS_001D
|
0042F8C0   C6431D00               mov     byte ptr [ebx+$1D], $00
0042F8C4   33C0                   xor     eax, eax

* Reference to field TPrinterCanvas.OFFS_000C
|
0042F8C6   89430C                 mov     [ebx+$0C], eax
0042F8C9   5B                     pop     ebx
0042F8CA   C3                     ret

*)
end;

procedure TPrinterCanvas._PROC_0042F8CC(Sender : TObject);
begin
(*
0042F8CC   53                     push    ebx
0042F8CD   8BD8                   mov     ebx, eax
0042F8CF   B201                   mov     dl, $01
0042F8D1   8BC3                   mov     eax, ebx

* Reference to: Printers.TPrinter.CheckPrinting(TPrinter;Boolean);
|
0042F8D3   E8C8FEFFFF             call    0042F7A0

* Reference to field TPrinterCanvas.OFFS_0020
|
0042F8D8   8B4320                 mov     eax, [ebx+$20]
0042F8DB   50                     push    eax

* Reference to: InitCommonControls.EndPage()
|
0042F8DC   E89F71FDFF             call    00406A80

* Reference to field TPrinterCanvas.OFFS_0020
|
0042F8E1   8B4320                 mov     eax, [ebx+$20]
0042F8E4   50                     push    eax

* Reference to: InitCommonControls.StartPage()
|
0042F8E5   E87673FDFF             call    00406C60
0042F8EA   FF430C                 inc     dword ptr [ebx+$0C]
0042F8ED   8BC3                   mov     eax, ebx

* Reference to: Printers.TPrinter.GetCanvas(TPrinter):TCanvas;
|
0042F8EF   E88C020000             call    0042FB80

* Reference to: ActiveX.PROPSETHDR_OSVER_KIND(DWORD):Word;
|
0042F8F4   E8976BFFFF             call    00426490
0042F8F9   5B                     pop     ebx
0042F8FA   C3                     ret

*)
end;

procedure TPrinterCanvas._PROC_0042F8FC(Sender : TObject);
begin
(*
0042F8FC   53                     push    ebx
0042F8FD   56                     push    esi
0042F8FE   8BF2                   mov     esi, edx
0042F900   8BD8                   mov     ebx, eax
0042F902   A034F94200             mov     al, byte ptr [$0042F934]

* Reference to field TPrinterCanvas.OFFS_001E
|
0042F907   88431E                 mov     [ebx+$1E], al
0042F90A   F7C601000000           test    esi, $00000001 
0042F910   7404                   jz      0042F916
0042F912   804B1E02               or      byte ptr [ebx+$1E], $02
0042F916   F7C600010000           test    esi, $00000100 
0042F91C   7404                   jz      0042F922
0042F91E   804B1E01               or      byte ptr [ebx+$1E], $01
0042F922   F7C600800000           test    esi, $00008000 
0042F928   7404                   jz      0042F92E
0042F92A   804B1E04               or      byte ptr [ebx+$1E], $04
0042F92E   5E                     pop     esi
0042F92F   5B                     pop     ebx
0042F930   C3                     ret

*)
end;

procedure TPrinterCanvas._PROC_0042F939(Sender : TObject);
begin
(*
0042F939   8BEC                   mov     ebp, esp
0042F93B   81C43CFFFFFF           add     esp, $FFFFFF3C
0042F941   53                     push    ebx
0042F942   56                     push    esi
0042F943   57                     push    edi
0042F944   33DB                   xor     ebx, ebx
0042F946   899D50FFFFFF           mov     [ebp+$FFFFFF50], ebx
0042F94C   899D4CFFFFFF           mov     [ebp+$FFFFFF4C], ebx
0042F952   894DF8                 mov     [ebp-$08], ecx
0042F955   8955FC                 mov     [ebp-$04], edx
0042F958   8BD8                   mov     ebx, eax
0042F95A   8B7508                 mov     esi, [ebp+$08]
0042F95D   33C0                   xor     eax, eax
0042F95F   55                     push    ebp
0042F960   686FFB4200             push    $0042FB6F

***** TRY
|
0042F965   64FF30                 push    dword ptr fs:[eax]
0042F968   648920                 mov     fs:[eax], esp
0042F96B   33D2                   xor     edx, edx
0042F96D   8BC3                   mov     eax, ebx

* Reference to: Printers.TPrinter.CheckPrinting(TPrinter;Boolean);
|
0042F96F   E82CFEFFFF             call    0042F7A0

* Reference to field TPrinterCanvas.OFFS_0028
|
0042F974   8B4328                 mov     eax, [ebx+$28]
0042F977   3BF0                   cmp     esi, eax
0042F979   7416                   jz      0042F991
0042F97B   85C0                   test    eax, eax
0042F97D   740F                   jz      0042F98E
0042F97F   50                     push    eax

* Reference to: GetModuleHandleA.GlobalUnlock()
|
0042F980   E86B6FFDFF             call    004068F0

* Reference to field TPrinterCanvas.OFFS_0028
|
0042F985   8B4328                 mov     eax, [ebx+$28]
0042F988   50                     push    eax

* Reference to: GetModuleHandleA.GlobalFree()
|
0042F989   E83A6FFDFF             call    004068C8

* Reference to field TPrinterCanvas.OFFS_0028
|
0042F98E   897328                 mov     [ebx+$28], esi

* Reference to field TPrinterCanvas.OFFS_0028
|
0042F991   8B7328                 mov     esi, [ebx+$28]
0042F994   85F6                   test    esi, esi
0042F996   7415                   jz      0042F9AD
0042F998   56                     push    esi

* Reference to: GetModuleHandleA.GlobalLock()
|
0042F999   E8326FFDFF             call    004068D0
0042F99E   8BF8                   mov     edi, eax

* Reference to field TPrinterCanvas.OFFS_0024
|
0042F9A0   897B24                 mov     [ebx+$24], edi
0042F9A3   8B5728                 mov     edx, [edi+$28]
0042F9A6   8BC3                   mov     eax, ebx

* Reference to: Printers.TPrinter.SetPrinterCapabilities(TPrinter;Integer);
|
0042F9A8   E84FFFFFFF             call    0042F8FC
0042F9AD   8BC3                   mov     eax, ebx

* Reference to: Printers.TPrinter.FreeFonts(TPrinter);
|
0042F9AF   E8CC060000             call    00430080

* Reference to field TPrinterCanvas.OFFS_002C
|
0042F9B4   8B432C                 mov     eax, [ebx+$2C]
0042F9B7   85C0                   test    eax, eax
0042F9B9   740B                   jz      0042F9C6
0042F9BB   50                     push    eax

* Reference to: GetFileVersionInfoA.ClosePrinter()
|
0042F9BC   E857F7FFFF             call    0042F118
0042F9C1   33C0                   xor     eax, eax

* Reference to field TPrinterCanvas.OFFS_002C
|
0042F9C3   89432C                 mov     [ebx+$2C], eax
0042F9C6   33D2                   xor     edx, edx
0042F9C8   8BC3                   mov     eax, ebx

* Reference to: Printers.TPrinter.SetState(TPrinter;TPrinterState);
|
0042F9CA   E8A5FCFFFF             call    0042F674
0042F9CF   C745F4FFFFFFFF         mov     dword ptr [ebp-$0C], $FFFFFFFF
0042F9D6   8BC3                   mov     eax, ebx

* Reference to: Printers.TPrinter.GetPrinters(TPrinter):TStrings;
|
0042F9D8   E827020000             call    0042FC04
0042F9DD   8945F0                 mov     [ebp-$10], eax
0042F9E0   8B45F0                 mov     eax, [ebp-$10]
0042F9E3   8B10                   mov     edx, [eax]

* Possible reference to virtual method TPrinterCanvas.OFFS_14
|
0042F9E5   FF5214                 call    dword ptr [edx+$14]
0042F9E8   8BF8                   mov     edi, eax
0042F9EA   4F                     dec     edi
0042F9EB   85FF                   test    edi, edi
0042F9ED   7C3E                   jl      0042FA2D
0042F9EF   47                     inc     edi
0042F9F0   33F6                   xor     esi, esi
0042F9F2   8B450C                 mov     eax, [ebp+$0C]
0042F9F5   50                     push    eax
0042F9F6   8BD6                   mov     edx, esi
0042F9F8   8B45F0                 mov     eax, [ebp-$10]
0042F9FB   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TPrinterCanvas.OFFS_18
|
0042F9FD   FF5118                 call    dword ptr [ecx+$18]
0042FA00   8B4DFC                 mov     ecx, [ebp-$04]
0042FA03   8B55F8                 mov     edx, [ebp-$08]

* Reference to: Printers.TPrinterDevice.IsEqual(TPrinterDevice;PChar;PChar;PChar):Boolean;
|
0042FA06   E875F9FFFF             call    0042F380
0042FA0B   84C0                   test    al, al
0042FA0D   741A                   jz      0042FA29
0042FA0F   8BD6                   mov     edx, esi
0042FA11   8B45F0                 mov     eax, [ebp-$10]
0042FA14   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TPrinterCanvas.OFFS_18
|
0042FA16   FF5118                 call    dword ptr [ecx+$18]
0042FA19   83C00C                 add     eax, +$0C
0042FA1C   8B550C                 mov     edx, [ebp+$0C]

* Reference to: System.@LStrFromPChar(String;String;PAnsiChar);
|
0042FA1F   E84C49FDFF             call    00404370
0042FA24   8975F4                 mov     [ebp-$0C], esi
0042FA27   EB04                   jmp     0042FA2D
0042FA29   46                     inc     esi
0042FA2A   4F                     dec     edi
0042FA2B   75C5                   jnz     0042F9F2
0042FA2D   837DF4FF               cmp     dword ptr [ebp-$0C], -$01
0042FA31   757F                   jnz     0042FAB2

* Reference to field TPrinterCanvas.OFFS_0010
|
0042FA33   8B4310                 mov     eax, [ebx+$10]
0042FA36   8B10                   mov     edx, [eax]
0042FA38   FF5214                 call    dword ptr [edx+$14]
0042FA3B   8945F4                 mov     [ebp-$0C], eax
0042FA3E   8B45FC                 mov     eax, [ebp-$04]
0042FA41   50                     push    eax
0042FA42   8B450C                 mov     eax, [ebp+$0C]
0042FA45   50                     push    eax
0042FA46   8B4DF8                 mov     ecx, [ebp-$08]
0042FA49   B201                   mov     dl, $01

* Reference to class TPrinterDevice
|
0042FA4B   A1A0F24200             mov     eax, dword ptr [$0042F2A0]

* Reference to: Printers.TPrinterDevice.Create(TPrinterDevice;boolean;PChar;PChar;PChar);
|
0042FA50   E8CBF8FFFF             call    0042F320
0042FA55   50                     push    eax
0042FA56   8D8550FFFFFF           lea     eax, [ebp+$FFFFFF50]
0042FA5C   50                     push    eax
0042FA5D   8D954CFFFFFF           lea     edx, [ebp+$FFFFFF4C]
0042FA63   A114004A00             mov     eax, dword ptr [$004A0014]

* Reference to: System.LoadResString(PResStringRec):String;
|
0042FA68   E86F67FDFF             call    004061DC
0042FA6D   8B854CFFFFFF           mov     eax, [ebp+$FFFFFF4C]
0042FA73   8B55FC                 mov     edx, [ebp-$04]
0042FA76   89953CFFFFFF           mov     [ebp+$FFFFFF3C], edx
0042FA7C   C68540FFFFFF06         mov     byte ptr [ebp+$FFFFFF40], $06
0042FA83   8B550C                 mov     edx, [ebp+$0C]
0042FA86   899544FFFFFF           mov     [ebp+$FFFFFF44], edx
0042FA8C   C68548FFFFFF06         mov     byte ptr [ebp+$FFFFFF48], $06
0042FA93   8D953CFFFFFF           lea     edx, [ebp+$FFFFFF3C]
0042FA99   B901000000             mov     ecx, $00000001

|
0042FA9E   E80D9EFDFF             call    004098B0
0042FAA3   8B9550FFFFFF           mov     edx, [ebp+$FFFFFF50]

* Reference to field TPrinterCanvas.OFFS_0010
|
0042FAA9   8B4310                 mov     eax, [ebx+$10]
0042FAAC   59                     pop     ecx
0042FAAD   8B30                   mov     esi, [eax]
0042FAAF   FF563C                 call    dword ptr [esi+$3C]
0042FAB2   8B45F4                 mov     eax, [ebp-$0C]

* Reference to field TPrinterCanvas.OFFS_0014
|
0042FAB5   894314                 mov     [ebx+$14], eax
0042FAB8   6A00                   push    $00

* Reference to field TPrinterCanvas.OFFS_002C
|
0042FABA   8D432C                 lea     eax, [ebx+$2C]
0042FABD   50                     push    eax
0042FABE   8B45FC                 mov     eax, [ebp-$04]
0042FAC1   50                     push    eax

* Reference to: GetFileVersionInfoA.OpenPrinterA()
|
0042FAC2   E869F6FFFF             call    0042F130
0042FAC7   85C0                   test    eax, eax
0042FAC9   0F8482000000           jz      0042FB51

* Reference to field TPrinterCanvas.OFFS_0028
|
0042FACF   837B2800               cmp     dword ptr [ebx+$28], +$00
0042FAD3   7569                   jnz     0042FB3E
0042FAD5   6A00                   push    $00
0042FAD7   8D8554FFFFFF           lea     eax, [ebp+$FFFFFF54]
0042FADD   50                     push    eax
0042FADE   8D8554FFFFFF           lea     eax, [ebp+$FFFFFF54]
0042FAE4   50                     push    eax
0042FAE5   8B45FC                 mov     eax, [ebp-$04]
0042FAE8   50                     push    eax

* Reference to field TPrinterCanvas.OFFS_002C
|
0042FAE9   8B432C                 mov     eax, [ebx+$2C]
0042FAEC   50                     push    eax
0042FAED   6A00                   push    $00

* Reference to: GetFileVersionInfoA.DocumentPropertiesA()
|
0042FAEF   E82CF6FFFF             call    0042F120
0042FAF4   50                     push    eax
0042FAF5   6A42                   push    $42

* Reference to: GetModuleHandleA.GlobalAlloc()
|
0042FAF7   E8B46DFDFF             call    004068B0
0042FAFC   8BF0                   mov     esi, eax

* Reference to field TPrinterCanvas.OFFS_0028
|
0042FAFE   897328                 mov     [ebx+$28], esi
0042FB01   85F6                   test    esi, esi
0042FB03   7439                   jz      0042FB3E
0042FB05   56                     push    esi

* Reference to: GetModuleHandleA.GlobalLock()
|
0042FB06   E8C56DFDFF             call    004068D0
0042FB0B   8BF8                   mov     edi, eax

* Reference to field TPrinterCanvas.OFFS_0024
|
0042FB0D   897B24                 mov     [ebx+$24], edi
0042FB10   6A02                   push    $02
0042FB12   57                     push    edi
0042FB13   57                     push    edi
0042FB14   8B45FC                 mov     eax, [ebp-$04]
0042FB17   50                     push    eax

* Reference to field TPrinterCanvas.OFFS_002C
|
0042FB18   8B432C                 mov     eax, [ebx+$2C]
0042FB1B   50                     push    eax
0042FB1C   6A00                   push    $00

* Reference to: GetFileVersionInfoA.DocumentPropertiesA()
|
0042FB1E   E8FDF5FFFF             call    0042F120
0042FB23   85C0                   test    eax, eax
0042FB25   7D17                   jnl     0042FB3E

* Reference to field TPrinterCanvas.OFFS_0028
|
0042FB27   8B4328                 mov     eax, [ebx+$28]
0042FB2A   50                     push    eax

* Reference to: GetModuleHandleA.GlobalUnlock()
|
0042FB2B   E8C06DFDFF             call    004068F0

* Reference to field TPrinterCanvas.OFFS_0028
|
0042FB30   8B4328                 mov     eax, [ebx+$28]
0042FB33   50                     push    eax

* Reference to: GetModuleHandleA.GlobalFree()
|
0042FB34   E88F6DFDFF             call    004068C8
0042FB39   33C0                   xor     eax, eax

* Reference to field TPrinterCanvas.OFFS_0028
|
0042FB3B   894328                 mov     [ebx+$28], eax

* Reference to field TPrinterCanvas.OFFS_0028
|
0042FB3E   837B2800               cmp     dword ptr [ebx+$28], +$00
0042FB42   740D                   jz      0042FB51

* Reference to field TPrinterCanvas.OFFS_0024
|
0042FB44   8B4324                 mov     eax, [ebx+$24]
0042FB47   8B5028                 mov     edx, [eax+$28]
0042FB4A   8BC3                   mov     eax, ebx

* Reference to: Printers.TPrinter.SetPrinterCapabilities(TPrinter;Integer);
|
0042FB4C   E8ABFDFFFF             call    0042F8FC
0042FB51   33C0                   xor     eax, eax
0042FB53   5A                     pop     edx
0042FB54   59                     pop     ecx
0042FB55   59                     pop     ecx
0042FB56   648910                 mov     fs:[eax], edx

****** FINALLY
|
0042FB59   6876FB4200             push    $0042FB76
0042FB5E   8D854CFFFFFF           lea     eax, [ebp+$FFFFFF4C]
0042FB64   BA02000000             mov     edx, $00000002

* Reference to: System.@LStrArrayClr(void;void;Integer);
|
0042FB69   E82E46FDFF             call    0040419C
0042FB6E   C3                     ret


* Reference to: System.@HandleFinally;
|
0042FB6F   E90840FDFF             jmp     00403B7C
0042FB74   EBE8                   jmp     0042FB5E

****** END
|
0042FB76   5F                     pop     edi
0042FB77   5E                     pop     esi
0042FB78   5B                     pop     ebx
0042FB79   8BE5                   mov     esp, ebp
0042FB7B   5D                     pop     ebp
0042FB7C   C20800                 ret     $0008

*)
end;

procedure TPrinterCanvas._PROC_0042FB80(Sender : TObject);
begin
(*
0042FB80   53                     push    ebx
0042FB81   8BD8                   mov     ebx, eax

* Reference to field TPrinterCanvas.OFFS_0004
|
0042FB83   837B0400               cmp     dword ptr [ebx+$04], +$00
0042FB87   7511                   jnz     0042FB9A
0042FB89   8BCB                   mov     ecx, ebx
0042FB8B   B201                   mov     dl, $01

* Reference to class TPrinterCanvas
|
0042FB8D   A104F44200             mov     eax, dword ptr [$0042F404]

* Reference to: Printers.TPrinterCanvas.Create(TPrinterCanvas;boolean;TPrinter);
|
0042FB92   E85DF9FFFF             call    0042F4F4

* Reference to field TPrinterCanvas.OFFS_0004
|
0042FB97   894304                 mov     [ebx+$04], eax

* Reference to field TPrinterCanvas.OFFS_0004
|
0042FB9A   8B4304                 mov     eax, [ebx+$04]
0042FB9D   5B                     pop     ebx
0042FB9E   C3                     ret

*)
end;

procedure TPrinterCanvas._PROC_0042FBA0(Sender : TObject);
begin
(*
0042FBA0   53                     push    ebx
0042FBA1   8BD8                   mov     ebx, eax
0042FBA3   B201                   mov     dl, $01
0042FBA5   8BC3                   mov     eax, ebx

* Reference to: Printers.TPrinter.SetState(TPrinter;TPrinterState);
|
0042FBA7   E8C8FAFFFF             call    0042F674

* Reference to field TPrinterCanvas.OFFS_0020
|
0042FBAC   8B4320                 mov     eax, [ebx+$20]
0042FBAF   5B                     pop     ebx
0042FBB0   C3                     ret

*)
end;

procedure TPrinterCanvas._PROC_0042FBB4(Sender : TObject);
begin
(*
0042FBB4   53                     push    ebx
0042FBB5   8BD8                   mov     ebx, eax
0042FBB7   B201                   mov     dl, $01
0042FBB9   8BC3                   mov     eax, ebx

* Reference to: Printers.TPrinter.SetState(TPrinter;TPrinterState);
|
0042FBBB   E8B4FAFFFF             call    0042F674
0042FBC0   6A0A                   push    $0A

* Reference to field TPrinterCanvas.OFFS_0020
|
0042FBC2   8B4320                 mov     eax, [ebx+$20]
0042FBC5   50                     push    eax

* Reference to: InitCommonControls.GetDeviceCaps()
|
0042FBC6   E80D6FFDFF             call    00406AD8
0042FBCB   5B                     pop     ebx
0042FBCC   C3                     ret

*)
end;

procedure TPrinterCanvas._PROC_0042FBD0(Sender : TObject);
begin
(*
0042FBD0   53                     push    ebx
0042FBD1   8BD8                   mov     ebx, eax
0042FBD3   B201                   mov     dl, $01
0042FBD5   8BC3                   mov     eax, ebx

* Reference to: Printers.TPrinter.SetState(TPrinter;TPrinterState);
|
0042FBD7   E898FAFFFF             call    0042F674
0042FBDC   6A08                   push    $08

* Reference to field TPrinterCanvas.OFFS_0020
|
0042FBDE   8B4320                 mov     eax, [ebx+$20]
0042FBE1   50                     push    eax

* Reference to: InitCommonControls.GetDeviceCaps()
|
0042FBE2   E8F16EFDFF             call    00406AD8
0042FBE7   5B                     pop     ebx
0042FBE8   C3                     ret

*)
end;

procedure TPrinterCanvas._PROC_0042FBEC(Sender : TObject);
begin
(*
0042FBEC   53                     push    ebx
0042FBED   8BD8                   mov     ebx, eax

* Reference to field TPrinterCanvas.OFFS_0014
|
0042FBEF   837B14FF               cmp     dword ptr [ebx+$14], -$01
0042FBF3   7507                   jnz     0042FBFC
0042FBF5   8BC3                   mov     eax, ebx

* Reference to: Printers.TPrinter.SetToDefaultPrinter(TPrinter);
|
0042FBF7   E848020000             call    0042FE44

* Reference to field TPrinterCanvas.OFFS_0014
|
0042FBFC   8B4314                 mov     eax, [ebx+$14]
0042FBFF   5B                     pop     ebx
0042FC00   C3                     ret

*)
end;

procedure TPrinterCanvas._PROC_0042FC04(Sender : TObject);
begin
(*
0042FC04   55                     push    ebp
0042FC05   8BEC                   mov     ebp, esp
0042FC07   83C4C8                 add     esp, -$38
0042FC0A   53                     push    ebx
0042FC0B   56                     push    esi
0042FC0C   57                     push    edi
0042FC0D   33D2                   xor     edx, edx
0042FC0F   8955DC                 mov     [ebp-$24], edx
0042FC12   8955D8                 mov     [ebp-$28], edx
0042FC15   8955E0                 mov     [ebp-$20], edx
0042FC18   8945FC                 mov     [ebp-$04], eax
0042FC1B   33C0                   xor     eax, eax
0042FC1D   55                     push    ebp

* Possible String Reference to: 'ÈD=˝ˇÎÎã«_^[ãÂ]√êUãÏÅƒ‹˚ˇˇSVW3“âï‹˚
|                                ˇˇâï‡˚ˇˇâï‰˚ˇˇâE¸3¿Uh!'
|
0042FC1E   6833FE4200             push    $0042FE33

***** TRY
|
0042FC23   64FF30                 push    dword ptr fs:[eax]
0042FC26   648920                 mov     fs:[eax], esp
0042FC29   8B45FC                 mov     eax, [ebp-$04]

* Reference to field TPrinterCanvas.OFFS_0010
|
0042FC2C   83781000               cmp     dword ptr [eax+$10], +$00
0042FC30   0F85DC010000           jnz     0042FE12
0042FC36   B201                   mov     dl, $01

* Reference to class TStringList
|
0042FC38   A1DC7C4100             mov     eax, dword ptr [$00417CDC]

* Reference to: System.TObject.Create(TObject;Boolean);
|
0042FC3D   E87637FDFF             call    004033B8
0042FC42   8BD8                   mov     ebx, eax
0042FC44   8B45FC                 mov     eax, [ebp-$04]

* Reference to field TPrinterCanvas.OFFS_0010
|
0042FC47   895810                 mov     [eax+$10], ebx
0042FC4A   8BFB                   mov     edi, ebx
0042FC4C   33D2                   xor     edx, edx
0042FC4E   55                     push    ebp
0042FC4F   68F0FD4200             push    $0042FDF0

***** TRY
|
0042FC54   64FF32                 push    dword ptr fs:[edx]
0042FC57   648922                 mov     fs:[edx], esp
0042FC5A   A18C044A00             mov     eax, dword ptr [$004A048C]
0042FC5F   833802                 cmp     dword ptr [eax], +$02
0042FC62   7509                   jnz     0042FC6D
0042FC64   BE06000000             mov     esi, $00000006
0042FC69   B304                   mov     bl, $04
0042FC6B   EB07                   jmp     0042FC74
0042FC6D   BE02000000             mov     esi, $00000002
0042FC72   B305                   mov     bl, $05
0042FC74   33C0                   xor     eax, eax
0042FC76   8945EC                 mov     [ebp-$14], eax
0042FC79   8D45E8                 lea     eax, [ebp-$18]
0042FC7C   50                     push    eax
0042FC7D   8D45EC                 lea     eax, [ebp-$14]
0042FC80   50                     push    eax
0042FC81   6A00                   push    $00
0042FC83   6A00                   push    $00
0042FC85   33C0                   xor     eax, eax
0042FC87   8AC3                   mov     al, bl
0042FC89   50                     push    eax
0042FC8A   6A00                   push    $00
0042FC8C   56                     push    esi

* Reference to: GetFileVersionInfoA.EnumPrintersA()
|
0042FC8D   E896F4FFFF             call    0042F128
0042FC92   837DEC00               cmp     dword ptr [ebp-$14], +$00
0042FC96   750D                   jnz     0042FCA5
0042FC98   33C0                   xor     eax, eax
0042FC9A   5A                     pop     edx
0042FC9B   59                     pop     ecx
0042FC9C   59                     pop     ecx
0042FC9D   648910                 mov     fs:[eax], edx
0042FCA0   E973010000             jmp     0042FE18
0042FCA5   8B45EC                 mov     eax, [ebp-$14]

* Reference to: System.@GetMem(Integer):Pointer;
|
0042FCA8   E8E32AFDFF             call    00402790
0042FCAD   8945F4                 mov     [ebp-$0C], eax
0042FCB0   33D2                   xor     edx, edx
0042FCB2   55                     push    ebp
0042FCB3   68DFFD4200             push    $0042FDDF

***** TRY
|
0042FCB8   64FF32                 push    dword ptr fs:[edx]
0042FCBB   648922                 mov     fs:[edx], esp
0042FCBE   8D45E8                 lea     eax, [ebp-$18]
0042FCC1   50                     push    eax
0042FCC2   8D45EC                 lea     eax, [ebp-$14]
0042FCC5   50                     push    eax
0042FCC6   8B45EC                 mov     eax, [ebp-$14]
0042FCC9   50                     push    eax
0042FCCA   8B45F4                 mov     eax, [ebp-$0C]
0042FCCD   50                     push    eax
0042FCCE   33C0                   xor     eax, eax
0042FCD0   8AC3                   mov     al, bl
0042FCD2   50                     push    eax
0042FCD3   6A00                   push    $00
0042FCD5   56                     push    esi

* Reference to: GetFileVersionInfoA.EnumPrintersA()
|
0042FCD6   E84DF4FFFF             call    0042F128
0042FCDB   85C0                   test    eax, eax
0042FCDD   7512                   jnz     0042FCF1

* Reference to: System.@TryFinallyExit;
|
0042FCDF   E87C3FFDFF             call    00403C60
0042FCE4   33C0                   xor     eax, eax
0042FCE6   5A                     pop     edx
0042FCE7   59                     pop     ecx
0042FCE8   59                     pop     ecx
0042FCE9   648910                 mov     fs:[eax], edx
0042FCEC   E927010000             jmp     0042FE18
0042FCF1   8B45F4                 mov     eax, [ebp-$0C]
0042FCF4   8945F0                 mov     [ebp-$10], eax
0042FCF7   8B45E8                 mov     eax, [ebp-$18]
0042FCFA   48                     dec     eax
0042FCFB   85C0                   test    eax, eax
0042FCFD   0F8CC3000000           jl      0042FDC6
0042FD03   40                     inc     eax
0042FD04   8945E4                 mov     [ebp-$1C], eax
0042FD07   80FB04                 cmp     bl, $04
0042FD0A   7536                   jnz     0042FD42
0042FD0C   8B75F0                 mov     esi, [ebp-$10]
0042FD0F   8B3E                   mov     edi, [esi]
0042FD11   57                     push    edi
0042FD12   6A00                   push    $00
0042FD14   33C9                   xor     ecx, ecx
0042FD16   B201                   mov     dl, $01

* Reference to class TPrinterDevice
|
0042FD18   A1A0F24200             mov     eax, dword ptr [$0042F2A0]

* Reference to: Printers.TPrinterDevice.Create(TPrinterDevice;boolean;PChar;PChar;PChar);
|
0042FD1D   E8FEF5FFFF             call    0042F320
0042FD22   50                     push    eax
0042FD23   8D45E0                 lea     eax, [ebp-$20]
0042FD26   8BD7                   mov     edx, edi

* Reference to: System.@LStrFromPChar(String;String;PAnsiChar);
|
0042FD28   E84346FDFF             call    00404370
0042FD2D   8B55E0                 mov     edx, [ebp-$20]
0042FD30   8B45FC                 mov     eax, [ebp-$04]

* Reference to field TPrinterCanvas.OFFS_0010
|
0042FD33   8B4010                 mov     eax, [eax+$10]
0042FD36   59                     pop     ecx
0042FD37   8B30                   mov     esi, [eax]
0042FD39   FF563C                 call    dword ptr [esi+$3C]
0042FD3C   8345F00C               add     dword ptr [ebp-$10], +$0C
0042FD40   EB7B                   jmp     0042FDBD
0042FD42   8B75F0                 mov     esi, [ebp-$10]
0042FD45   8B4604                 mov     eax, [esi+$04]
0042FD48   8945F8                 mov     [ebp-$08], eax
0042FD4B   8D45F8                 lea     eax, [ebp-$08]

* Reference to: Printers.FetchStr(PChar;PChar):PChar;
|
0042FD4E   E8DDF4FFFF             call    0042F230
0042FD53   8BF8                   mov     edi, eax
0042FD55   EB5D                   jmp     0042FDB4
0042FD57   8B06                   mov     eax, [esi]
0042FD59   50                     push    eax
0042FD5A   57                     push    edi
0042FD5B   33C9                   xor     ecx, ecx
0042FD5D   B201                   mov     dl, $01

* Reference to class TPrinterDevice
|
0042FD5F   A1A0F24200             mov     eax, dword ptr [$0042F2A0]

* Reference to: Printers.TPrinterDevice.Create(TPrinterDevice;boolean;PChar;PChar;PChar);
|
0042FD64   E8B7F5FFFF             call    0042F320
0042FD69   50                     push    eax
0042FD6A   8D45DC                 lea     eax, [ebp-$24]
0042FD6D   50                     push    eax
0042FD6E   8D55D8                 lea     edx, [ebp-$28]
0042FD71   A114004A00             mov     eax, dword ptr [$004A0014]

* Reference to: System.LoadResString(PResStringRec):String;
|
0042FD76   E86164FDFF             call    004061DC
0042FD7B   8B45D8                 mov     eax, [ebp-$28]
0042FD7E   8B16                   mov     edx, [esi]
0042FD80   8955C8                 mov     [ebp-$38], edx
0042FD83   C645CC06               mov     byte ptr [ebp-$34], $06
0042FD87   897DD0                 mov     [ebp-$30], edi
0042FD8A   C645D406               mov     byte ptr [ebp-$2C], $06
0042FD8E   8D55C8                 lea     edx, [ebp-$38]
0042FD91   B901000000             mov     ecx, $00000001

|
0042FD96   E8159BFDFF             call    004098B0
0042FD9B   8B55DC                 mov     edx, [ebp-$24]
0042FD9E   8B45FC                 mov     eax, [ebp-$04]

* Reference to field TPrinterCanvas.OFFS_0010
|
0042FDA1   8B4010                 mov     eax, [eax+$10]
0042FDA4   59                     pop     ecx
0042FDA5   8B38                   mov     edi, [eax]
0042FDA7   FF573C                 call    dword ptr [edi+$3C]
0042FDAA   8D45F8                 lea     eax, [ebp-$08]

* Reference to: Printers.FetchStr(PChar;PChar):PChar;
|
0042FDAD   E87EF4FFFF             call    0042F230
0042FDB2   8BF8                   mov     edi, eax
0042FDB4   803F00                 cmp     byte ptr [edi], $00
0042FDB7   759E                   jnz     0042FD57
0042FDB9   8345F014               add     dword ptr [ebp-$10], +$14
0042FDBD   FF4DE4                 dec     dword ptr [ebp-$1C]
0042FDC0   0F8541FFFFFF           jnz     0042FD07
0042FDC6   33C0                   xor     eax, eax
0042FDC8   5A                     pop     edx
0042FDC9   59                     pop     ecx
0042FDCA   59                     pop     ecx
0042FDCB   648910                 mov     fs:[eax], edx

****** FINALLY
|
0042FDCE   68E6FD4200             push    $0042FDE6
0042FDD3   8B55EC                 mov     edx, [ebp-$14]
0042FDD6   8B45F4                 mov     eax, [ebp-$0C]

* Reference to: System.@FreeMem(Pointer):Integer;
|
0042FDD9   E8D229FDFF             call    004027B0
0042FDDE   C3                     ret


* Reference to: System.@HandleFinally;
|
0042FDDF   E9983DFDFF             jmp     00403B7C
0042FDE4   EBED                   jmp     0042FDD3

****** END
|
0042FDE6   33C0                   xor     eax, eax
0042FDE8   5A                     pop     edx
0042FDE9   59                     pop     ecx
0042FDEA   59                     pop     ecx
0042FDEB   648910                 mov     fs:[eax], edx
0042FDEE   EB22                   jmp     0042FE12

* Reference to: System.@HandleAnyException;
|
0042FDF0   E9D33AFDFF             jmp     004038C8
0042FDF5   8B45FC                 mov     eax, [ebp-$04]

* Reference to field TPrinterCanvas.OFFS_0010
|
0042FDF8   8B4010                 mov     eax, [eax+$10]

* Reference to: System.TObject.Free(TObject);
|
0042FDFB   E8E835FDFF             call    004033E8
0042FE00   8B45FC                 mov     eax, [ebp-$04]
0042FE03   33D2                   xor     edx, edx

* Reference to field TPrinterCanvas.OFFS_0010
|
0042FE05   895010                 mov     [eax+$10], edx

* Reference to: System.@RaiseAgain;
|
0042FE08   E8CF3DFDFF             call    00403BDC

* Reference to: System.@DoneExcept;
|
0042FE0D   E81E3EFDFF             call    00403C30

****** END
|
0042FE12   8B45FC                 mov     eax, [ebp-$04]

* Reference to field TPrinterCanvas.OFFS_0010
|
0042FE15   8B7810                 mov     edi, [eax+$10]
0042FE18   33C0                   xor     eax, eax
0042FE1A   5A                     pop     edx
0042FE1B   59                     pop     ecx
0042FE1C   59                     pop     ecx
0042FE1D   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: 'ã«_^[ãÂ]√êUãÏÅƒ‹˚ˇˇSVW3“âï‹˚ˇˇâï‡˚ˇ
|                                ˇâï‰˚ˇˇâE¸3¿Uh!'
|
0042FE20   683AFE4200             push    $0042FE3A
0042FE25   8D45D8                 lea     eax, [ebp-$28]
0042FE28   BA03000000             mov     edx, $00000003

* Reference to: System.@LStrArrayClr(void;void;Integer);
|
0042FE2D   E86A43FDFF             call    0040419C
0042FE32   C3                     ret


* Reference to: System.@HandleFinally;
|
0042FE33   E9443DFDFF             jmp     00403B7C
0042FE38   EBEB                   jmp     0042FE25

****** END
|
0042FE3A   8BC7                   mov     eax, edi
0042FE3C   5F                     pop     edi
0042FE3D   5E                     pop     esi
0042FE3E   5B                     pop     ebx
0042FE3F   8BE5                   mov     esp, ebp
0042FE41   5D                     pop     ebp
0042FE42   C3                     ret

*)
end;

procedure TPrinterCanvas._PROC_0042FE44(Sender : TObject);
begin
(*
0042FE44   55                     push    ebp
0042FE45   8BEC                   mov     ebp, esp
0042FE47   81C4DCFBFFFF           add     esp, $FFFFFBDC
0042FE4D   53                     push    ebx
0042FE4E   56                     push    esi
0042FE4F   57                     push    edi
0042FE50   33D2                   xor     edx, edx
0042FE52   8995DCFBFFFF           mov     [ebp+$FFFFFBDC], edx
0042FE58   8995E0FBFFFF           mov     [ebp+$FFFFFBE0], edx
0042FE5E   8995E4FBFFFF           mov     [ebp+$FFFFFBE4], edx
0042FE64   8945FC                 mov     [ebp-$04], eax
0042FE67   33C0                   xor     eax, eax
0042FE69   55                     push    ebp

* Possible String Reference to: 'ÈV;˝ˇÎË_^[ãÂ]√'
|
0042FE6A   6821004300             push    $00430021

***** TRY
|
0042FE6F   64FF30                 push    dword ptr fs:[eax]
0042FE72   648920                 mov     fs:[eax], esp
0042FE75   33C0                   xor     eax, eax
0042FE77   8945F8                 mov     [ebp-$08], eax
0042FE7A   33C0                   xor     eax, eax
0042FE7C   8945F4                 mov     [ebp-$0C], eax
0042FE7F   8D45F4                 lea     eax, [ebp-$0C]
0042FE82   50                     push    eax
0042FE83   8D45F8                 lea     eax, [ebp-$08]
0042FE86   50                     push    eax
0042FE87   6A00                   push    $00
0042FE89   6A00                   push    $00
0042FE8B   6A05                   push    $05
0042FE8D   6A00                   push    $00
0042FE8F   6A01                   push    $01

* Reference to: GetFileVersionInfoA.EnumPrintersA()
|
0042FE91   E892F2FFFF             call    0042F128
0042FE96   85C0                   test    eax, eax
0042FE98   7536                   jnz     0042FED0

* Reference to: GetModuleHandleA.GetLastError()
|
0042FE9A   E87969FDFF             call    00406818
0042FE9F   83F87A                 cmp     eax, +$7A
0042FEA2   742C                   jz      0042FED0

* Reference to: GetModuleHandleA.GetLastError()
|
0042FEA4   E86F69FDFF             call    00406818
0042FEA9   83F87B                 cmp     eax, +$7B
0042FEAC   751D                   jnz     0042FECB
0042FEAE   8D95E4FBFFFF           lea     edx, [ebp+$FFFFFBE4]
0042FEB4   A164004A00             mov     eax, dword ptr [$004A0064]

* Reference to: System.LoadResString(PResStringRec):String;
|
0042FEB9   E81E63FDFF             call    004061DC
0042FEBE   8B85E4FBFFFF           mov     eax, [ebp+$FFFFFBE4]

* Reference to: AxCtrls.InvalidOperation(AnsiString);
|
0042FEC4   E89BF3FFFF             call    0042F264
0042FEC9   EB05                   jmp     0042FED0

* Reference to: SysUtils.RaiseLastOSError;
|
0042FECB   E898DAFDFF             call    0040D968
0042FED0   8B45F8                 mov     eax, [ebp-$08]

* Reference to: SysUtils.AllocMem(Cardinal):Pointer;
|
0042FED3   E80885FDFF             call    004083E0
0042FED8   8945E8                 mov     [ebp-$18], eax
0042FEDB   33C0                   xor     eax, eax
0042FEDD   55                     push    ebp

* Possible String Reference to: 'Èñ;˝ˇÎçï‹˚ˇˇ°d'
|
0042FEDE   68E1FF4200             push    $0042FFE1

***** TRY
|
0042FEE3   64FF30                 push    dword ptr fs:[eax]
0042FEE6   648920                 mov     fs:[eax], esp
0042FEE9   8D45F4                 lea     eax, [ebp-$0C]
0042FEEC   50                     push    eax
0042FEED   8D45F8                 lea     eax, [ebp-$08]
0042FEF0   50                     push    eax
0042FEF1   8B45F8                 mov     eax, [ebp-$08]
0042FEF4   50                     push    eax
0042FEF5   8B45E8                 mov     eax, [ebp-$18]
0042FEF8   50                     push    eax
0042FEF9   6A05                   push    $05
0042FEFB   6A00                   push    $00
0042FEFD   6A01                   push    $01

* Reference to: GetFileVersionInfoA.EnumPrintersA()
|
0042FEFF   E824F2FFFF             call    0042F128
0042FF04   837DF400               cmp     dword ptr [ebp-$0C], +$00
0042FF08   760A                   jbe     0042FF14
0042FF0A   8B45E8                 mov     eax, [ebp-$18]
0042FF0D   8B00                   mov     eax, [eax]
0042FF0F   8945EC                 mov     [ebp-$14], eax
0042FF12   EB34                   jmp     0042FF48
0042FF14   68FF030000             push    $000003FF
0042FF19   8D85E8FBFFFF           lea     eax, [ebp+$FFFFFBE8]
0042FF1F   50                     push    eax
0042FF20   6830004300             push    $00430030

* Possible String Reference to: 'device'
|
0042FF25   6834004300             push    $00430034

* Possible String Reference to: 'windows'
|
0042FF2A   683C004300             push    $0043003C

* Reference to: GetModuleHandleA.GetProfileStringA()
|
0042FF2F   E81469FDFF             call    00406848
0042FF34   8D85E8FBFFFF           lea     eax, [ebp+$FFFFFBE8]
0042FF3A   8945F0                 mov     [ebp-$10], eax
0042FF3D   8D45F0                 lea     eax, [ebp-$10]

* Reference to: Printers.FetchStr(PChar;PChar):PChar;
|
0042FF40   E8EBF2FFFF             call    0042F230
0042FF45   8945EC                 mov     [ebp-$14], eax
0042FF48   8B45FC                 mov     eax, [ebp-$04]

* Reference to: Printers.TPrinter.GetPrinters(TPrinter):TStrings;
|
0042FF4B   E8B4FCFFFF             call    0042FC04
0042FF50   8BF8                   mov     edi, eax
0042FF52   8BC7                   mov     eax, edi
0042FF54   8B10                   mov     edx, [eax]

* Possible reference to virtual method TPrinterCanvas.OFFS_14
|
0042FF56   FF5214                 call    dword ptr [edx+$14]
0042FF59   8BF0                   mov     esi, eax
0042FF5B   4E                     dec     esi
0042FF5C   85F6                   test    esi, esi
0042FF5E   7C6B                   jl      0042FFCB
0042FF60   46                     inc     esi
0042FF61   33DB                   xor     ebx, ebx
0042FF63   8BD3                   mov     edx, ebx
0042FF65   8BC7                   mov     eax, edi
0042FF67   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TPrinterCanvas.OFFS_18
|
0042FF69   FF5118                 call    dword ptr [ecx+$18]

* Reference to field TPrinterCanvas.OFFS_0008
|
0042FF6C   8B4008                 mov     eax, [eax+$08]
0042FF6F   50                     push    eax
0042FF70   8D85E0FBFFFF           lea     eax, [ebp+$FFFFFBE0]
0042FF76   8B55EC                 mov     edx, [ebp-$14]

* Reference to: System.@LStrFromPChar(String;String;PAnsiChar);
|
0042FF79   E8F243FDFF             call    00404370
0042FF7E   8B95E0FBFFFF           mov     edx, [ebp+$FFFFFBE0]
0042FF84   58                     pop     eax

* Reference to: SysUtils.AnsiSameStr(AnsiString;AnsiString):Boolean;
|
0042FF85   E8F286FDFF             call    0040867C
0042FF8A   84C0                   test    al, al
0042FF8C   7439                   jz      0042FFC7
0042FF8E   8BD3                   mov     edx, ebx
0042FF90   8BC7                   mov     eax, edi
0042FF92   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TPrinterCanvas.OFFS_18
|
0042FF94   FF5118                 call    dword ptr [ecx+$18]
0042FF97   8BD8                   mov     ebx, eax

* Reference to field TPrinterCanvas.OFFS_000C
|
0042FF99   8B430C                 mov     eax, [ebx+$0C]

* Reference to: System.@LStrToPChar(String):PAnsiChar;
|
0042FF9C   E89746FDFF             call    00404638
0042FFA1   50                     push    eax
0042FFA2   6A00                   push    $00

* Reference to field TPrinterCanvas.OFFS_0004
|
0042FFA4   8B4304                 mov     eax, [ebx+$04]

* Reference to: System.@LStrToPChar(String):PAnsiChar;
|
0042FFA7   E88C46FDFF             call    00404638
0042FFAC   50                     push    eax

* Reference to field TPrinterCanvas.OFFS_0008
|
0042FFAD   8B4308                 mov     eax, [ebx+$08]

* Reference to: System.@LStrToPChar(String):PAnsiChar;
|
0042FFB0   E88346FDFF             call    00404638
0042FFB5   8BD0                   mov     edx, eax
0042FFB7   8B45FC                 mov     eax, [ebp-$04]
0042FFBA   59                     pop     ecx

* Reference to: Printers.TPrinter.SetPrinter(TPrinter;PChar;PChar;PChar;Windows.THandle);
|
0042FFBB   E878F9FFFF             call    0042F938

* Reference to: System.@TryFinallyExit;
|
0042FFC0   E89B3CFDFF             call    00403C60
0042FFC5   EB3C                   jmp     00430003
0042FFC7   43                     inc     ebx
0042FFC8   4E                     dec     esi
0042FFC9   7598                   jnz     0042FF63
0042FFCB   33C0                   xor     eax, eax
0042FFCD   5A                     pop     edx
0042FFCE   59                     pop     ecx
0042FFCF   59                     pop     ecx
0042FFD0   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: 'çï‹˚ˇˇ°d'
|
0042FFD3   68E8FF4200             push    $0042FFE8
0042FFD8   8B45E8                 mov     eax, [ebp-$18]

* Reference to: System.@FreeMem(Pointer):Integer;
|
0042FFDB   E8D027FDFF             call    004027B0
0042FFE0   C3                     ret


* Reference to: System.@HandleFinally;
|
0042FFE1   E9963BFDFF             jmp     00403B7C
0042FFE6   EBF0                   jmp     0042FFD8

****** END
|
0042FFE8   8D95DCFBFFFF           lea     edx, [ebp+$FFFFFBDC]
0042FFEE   A164004A00             mov     eax, dword ptr [$004A0064]

* Reference to: System.LoadResString(PResStringRec):String;
|
0042FFF3   E8E461FDFF             call    004061DC
0042FFF8   8B85DCFBFFFF           mov     eax, [ebp+$FFFFFBDC]

* Reference to: AxCtrls.InvalidOperation(AnsiString);
|
0042FFFE   E861F2FFFF             call    0042F264
00430003   33C0                   xor     eax, eax
00430005   5A                     pop     edx
00430006   59                     pop     ecx
00430007   59                     pop     ecx
00430008   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '_^[ãÂ]√'
|
0043000B   6828004300             push    $00430028
00430010   8D85DCFBFFFF           lea     eax, [ebp+$FFFFFBDC]
00430016   BA03000000             mov     edx, $00000003

* Reference to: System.@LStrArrayClr(void;void;Integer);
|
0043001B   E87C41FDFF             call    0040419C
00430020   C3                     ret


* Reference to: System.@HandleFinally;
|
00430021   E9563BFDFF             jmp     00403B7C
00430026   EBE8                   jmp     00430010

****** END
|
00430028   5F                     pop     edi
00430029   5E                     pop     esi
0043002A   5B                     pop     ebx
0043002B   8BE5                   mov     esp, ebp
0043002D   5D                     pop     ebp
0043002E   C3                     ret

*)
end;

procedure TPrinterCanvas._PROC_00430081(Sender : TObject);
begin
(*
00430081   C008E8                 ror     byte ptr [eax], $E8
00430084   5C                     pop     esp
00430085   DEFD                   fdivp   st(5), st(0)
00430087   FFC3                   inc     ebx
00430089   8D4000                 lea     eax, [eax+$00]
0043008C   833DD4D7490000         cmp     dword ptr [$0049D7D4], +$00
00430093   7511                   jnz     004300A6
00430095   B201                   mov     dl, $01

* Reference to class TPrinter
|
00430097   A1C8F14200             mov     eax, dword ptr [$0042F1C8]

* Reference to: Printers.TPrinter.Create(TPrinter;boolean);
|
0043009C   E81BF5FFFF             call    0042F5BC
004300A1   A3D4D74900             mov     dword ptr [$0049D7D4], eax
004300A6   A1D4D74900             mov     eax, dword ptr [$0049D7D4]
004300AB   C3                     ret

*)
end;

procedure TPrinterCanvas._PROC_004300AC(Sender : TObject);
begin
(*
004300AC   55                     push    ebp
004300AD   8BEC                   mov     ebp, esp
004300AF   33C0                   xor     eax, eax
004300B1   55                     push    ebp
004300B2   68DD004300             push    $004300DD

***** TRY
|
004300B7   64FF30                 push    dword ptr fs:[eax]
004300BA   648920                 mov     fs:[eax], esp
004300BD   FF0548194A00           inc     dword ptr [$004A1948]
004300C3   750A                   jnz     004300CF
004300C5   A1D4D74900             mov     eax, dword ptr [$0049D7D4]

* Reference to: System.TObject.Free(TObject);
|
004300CA   E81933FDFF             call    004033E8
004300CF   33C0                   xor     eax, eax
004300D1   5A                     pop     edx
004300D2   59                     pop     ecx
004300D3   59                     pop     ecx
004300D4   648910                 mov     fs:[eax], edx

****** FINALLY
|
004300D7   68E4004300             push    $004300E4
004300DC   C3                     ret


* Reference to: System.@HandleFinally;
|
004300DD   E99A3AFDFF             jmp     00403B7C
004300E2   EBF8                   jmp     004300DC

****** END
|
004300E4   5D                     pop     ebp
004300E5   C3                     ret

*)
end;

procedure TPrinterCanvas._PROC_004300E8(Sender : TObject);
begin
(*
004300E8   832D48194A0001         sub     dword ptr [$004A1948], +$01
004300EF   C3                     ret

*)
end;

procedure TPrinterCanvas._PROC_004300F0(Sender : TObject);
begin
(*
004300F0   55                     push    ebp
004300F1   8BEC                   mov     ebp, esp
004300F3   833D74194A0000         cmp     dword ptr [$004A1974], +$00
004300FA   741A                   jz      00430116
004300FC   8B4514                 mov     eax, [ebp+$14]
004300FF   50                     push    eax
00430100   8B4510                 mov     eax, [ebp+$10]
00430103   50                     push    eax
00430104   8B450C                 mov     eax, [ebp+$0C]
00430107   50                     push    eax
00430108   8B4508                 mov     eax, [ebp+$08]
0043010B   50                     push    eax
0043010C   FF1574194A00           call    dword ptr [$004A1974]
00430112   85C0                   test    eax, eax
00430114   7504                   jnz     0043011A
00430116   33C0                   xor     eax, eax
00430118   EB02                   jmp     0043011C
0043011A   B001                   mov     al, $01
0043011C   F6D8                   neg     al
0043011E   1BC0                   sbb     eax, eax
00430120   5D                     pop     ebp
00430121   C21000                 ret     $0010

*)
end;

procedure TPrinterCanvas._PROC_00430124(Sender : TObject);
begin
(*
00430124   55                     push    ebp
00430125   8BEC                   mov     ebp, esp
00430127   833D78194A0000         cmp     dword ptr [$004A1978], +$00
0043012E   740E                   jz      0043013E
00430130   8B4508                 mov     eax, [ebp+$08]
00430133   50                     push    eax
00430134   FF1578194A00           call    dword ptr [$004A1978]
0043013A   85C0                   test    eax, eax
0043013C   7504                   jnz     00430142
0043013E   33C0                   xor     eax, eax
00430140   EB02                   jmp     00430144
00430142   B001                   mov     al, $01
00430144   F6D8                   neg     al
00430146   1BC0                   sbb     eax, eax
00430148   5D                     pop     ebp
00430149   C20400                 ret     $0004

*)
end;

procedure TPrinterCanvas._PROC_0043014C(Sender : TObject);
begin
(*
0043014C   53                     push    ebx
0043014D   56                     push    esi

* Possible String Reference to: 'comctl32.dll'
|
0043014E   68B0024300             push    $004302B0

* Reference to: GetModuleHandleA.GetModuleHandleA()
|
00430153   E8E066FDFF             call    00406838
00430158   8BD8                   mov     ebx, eax
0043015A   85DB                   test    ebx, ebx
0043015C   0F8448010000           jz      004302AA

* Possible String Reference to: 'InitializeFlatSB'
|
00430162   68C0024300             push    $004302C0
00430167   53                     push    ebx

* Reference to: GetModuleHandleA.GetProcAddress()
|
00430168   E8D366FDFF             call    00406840

* Reference to GlobalVar_004A1978
|
0043016D   A378194A00             mov     dword ptr [$004A1978], eax

* Possible String Reference to: 'UninitializeFlatSB'
|
00430172   68D4024300             push    $004302D4
00430177   53                     push    ebx

* Reference to: GetModuleHandleA.GetProcAddress()
|
00430178   E8C366FDFF             call    00406840

* Reference to GlobalVar_004A197C
|
0043017D   A37C194A00             mov     dword ptr [$004A197C], eax

* Possible String Reference to: 'FlatSB_GetScrollProp'
|
00430182   68E8024300             push    $004302E8
00430187   53                     push    ebx

* Reference to: GetModuleHandleA.GetProcAddress()
|
00430188   E8B366FDFF             call    00406840

* Reference to GlobalVar_004A1970
|
0043018D   A370194A00             mov     dword ptr [$004A1970], eax

* Possible String Reference to: 'FlatSB_SetScrollProp'
|
00430192   6800034300             push    $00430300
00430197   53                     push    ebx

* Reference to: GetModuleHandleA.GetProcAddress()
|
00430198   E8A366FDFF             call    00406840

* Reference to GlobalVar_004A1974
|
0043019D   A374194A00             mov     dword ptr [$004A1974], eax

* Possible String Reference to: 'FlatSB_EnableScrollBar'
|
004301A2   6818034300             push    $00430318
004301A7   53                     push    ebx

* Reference to: GetModuleHandleA.GetProcAddress()
|
004301A8   E89366FDFF             call    00406840
004301AD   8BF0                   mov     esi, eax
004301AF   89354C194A00           mov     [$004A194C], esi
004301B5   85F6                   test    esi, esi
004301B7   750A                   jnz     004301C3

* Possible String Reference to: 'ˇ%\'J'
|
004301B9   B8886D4000             mov     eax, $00406D88

* Reference to GlobalVar_004A194C
|
004301BE   A34C194A00             mov     dword ptr [$004A194C], eax

* Possible String Reference to: 'FlatSB_ShowScrollBar'
|
004301C3   6830034300             push    $00430330
004301C8   53                     push    ebx

* Reference to: GetModuleHandleA.GetProcAddress()
|
004301C9   E87266FDFF             call    00406840
004301CE   8BF0                   mov     esi, eax
004301D0   893550194A00           mov     [$004A1950], esi
004301D6   85F6                   test    esi, esi
004301D8   750A                   jnz     004301E4

* Possible String Reference to: 'ˇ%\%J'
|
004301DA   B898714000             mov     eax, $00407198

* Reference to GlobalVar_004A1950
|
004301DF   A350194A00             mov     dword ptr [$004A1950], eax

* Possible String Reference to: 'FlatSB_GetScrollRange'
|
004301E4   6848034300             push    $00430348
004301E9   53                     push    ebx

* Reference to: GetModuleHandleA.GetProcAddress()
|
004301EA   E85166FDFF             call    00406840
004301EF   8BF0                   mov     esi, eax
004301F1   893554194A00           mov     [$004A1954], esi
004301F7   85F6                   test    esi, esi
004301F9   750A                   jnz     00430205

* Possible String Reference to: 'ˇ%¨&J'
|
004301FB   B8E86E4000             mov     eax, $00406EE8

* Reference to GlobalVar_004A1954
|
00430200   A354194A00             mov     dword ptr [$004A1954], eax

* Possible String Reference to: 'FlatSB_GetScrollInfo'
|
00430205   6860034300             push    $00430360
0043020A   53                     push    ebx

* Reference to: GetModuleHandleA.GetProcAddress()
|
0043020B   E83066FDFF             call    00406840
00430210   8BF0                   mov     esi, eax
00430212   893558194A00           mov     [$004A1958], esi
00430218   85F6                   test    esi, esi
0043021A   750A                   jnz     00430226

* Possible String Reference to: 'ˇ%¥&J'
|
0043021C   B8D86E4000             mov     eax, $00406ED8

* Reference to GlobalVar_004A1958
|
00430221   A358194A00             mov     dword ptr [$004A1958], eax

* Possible String Reference to: 'FlatSB_GetScrollPos'
|
00430226   6878034300             push    $00430378
0043022B   53                     push    ebx

* Reference to: GetModuleHandleA.GetProcAddress()
|
0043022C   E80F66FDFF             call    00406840
00430231   8BF0                   mov     esi, eax
00430233   89355C194A00           mov     [$004A195C], esi
00430239   85F6                   test    esi, esi
0043023B   750A                   jnz     00430247

* Possible String Reference to: 'ˇ%∞&J'
|
0043023D   B8E06E4000             mov     eax, $00406EE0

* Reference to GlobalVar_004A195C
|
00430242   A35C194A00             mov     dword ptr [$004A195C], eax

* Possible String Reference to: 'FlatSB_SetScrollPos'
|
00430247   688C034300             push    $0043038C
0043024C   53                     push    ebx

* Reference to: GetModuleHandleA.GetProcAddress()
|
0043024D   E8EE65FDFF             call    00406840
00430252   8BF0                   mov     esi, eax
00430254   893560194A00           mov     [$004A1960], esi
0043025A   85F6                   test    esi, esi
0043025C   750A                   jnz     00430268

* Possible String Reference to: 'ˇ%à%J'
|
0043025E   B840714000             mov     eax, $00407140

* Reference to GlobalVar_004A1960
|
00430263   A360194A00             mov     dword ptr [$004A1960], eax

* Possible String Reference to: 'FlatSB_SetScrollInfo'
|
00430268   68A0034300             push    $004303A0
0043026D   53                     push    ebx

* Reference to: GetModuleHandleA.GetProcAddress()
|
0043026E   E8CD65FDFF             call    00406840
00430273   8BF0                   mov     esi, eax
00430275   893564194A00           mov     [$004A1964], esi
0043027B   85F6                   test    esi, esi
0043027D   750A                   jnz     00430289

* Possible String Reference to: 'ˇ%å%J'
|
0043027F   B838714000             mov     eax, $00407138

* Reference to GlobalVar_004A1964
|
00430284   A364194A00             mov     dword ptr [$004A1964], eax

* Possible String Reference to: 'FlatSB_SetScrollRange'
|
00430289   68B8034300             push    $004303B8
0043028E   53                     push    ebx

* Reference to: GetModuleHandleA.GetProcAddress()
|
0043028F   E8AC65FDFF             call    00406840
00430294   8BF0                   mov     esi, eax
00430296   893568194A00           mov     [$004A1968], esi
0043029C   85F6                   test    esi, esi
0043029E   750A                   jnz     004302AA

* Possible String Reference to: 'ˇ%Ñ%J'
|
004302A0   B848714000             mov     eax, $00407148

* Reference to GlobalVar_004A1968
|
004302A5   A368194A00             mov     dword ptr [$004A1968], eax
004302AA   5E                     pop     esi
004302AB   5B                     pop     ebx
004302AC   C3                     ret

*)
end;

procedure TPrinterCanvas._PROC_004302D5(Sender : TObject);
begin
(*
004302D5   6E                     outsb
004302D6   696E697469616C         imul    ebp, [esi+$69], $6C616974
004302DD   697A65466C6174         imul    edi, [edx+$65], $74616C46
004302E4   53                     push    ebx
004302E5   42                     inc     edx
004302E6   0000                   add     [eax], al

*)
end;

procedure TPrinterCanvas._PROC_004303D1(Sender : TObject);
begin
(*
004303D1   8BEC                   mov     ebp, esp
004303D3   33C0                   xor     eax, eax
004303D5   55                     push    ebp
004303D6   68F5034300             push    $004303F5

***** TRY
|
004303DB   64FF30                 push    dword ptr fs:[eax]
004303DE   648920                 mov     fs:[eax], esp
004303E1   FF056C194A00           inc     dword ptr [$004A196C]
004303E7   33C0                   xor     eax, eax
004303E9   5A                     pop     edx
004303EA   59                     pop     ecx
004303EB   59                     pop     ecx
004303EC   648910                 mov     fs:[eax], edx

****** FINALLY
|
004303EF   68FC034300             push    $004303FC
004303F4   C3                     ret


* Reference to: System.@HandleFinally;
|
004303F5   E98237FDFF             jmp     00403B7C
004303FA   EBF8                   jmp     004303F4

****** END
|
004303FC   5D                     pop     ebp
004303FD   C3                     ret

*)
end;

procedure TPrinterCanvas._PROC_00430400(Sender : TObject);
begin
(*
00430400   832D6C194A0001         sub     dword ptr [$004A196C], +$01
00430407   7305                   jnb     0043040E

* Reference to: FlatSB.InitFlatSB;
|
00430409   E83EFDFFFF             call    0043014C
0043040E   C3                     ret

*)
end;

procedure TPrinterCanvas._PROC_00430410(Sender : TObject);
begin
(*
00430410   5C                     pop     esp
00430411   0443                   add     al, +$43
00430413   0000                   add     [eax], al

*)
end;

procedure TPrinterCanvas._PROC_0042F4F4(Sender : TObject);
begin
(*
0042F4F4   53                     push    ebx
0042F4F5   56                     push    esi
0042F4F6   57                     push    edi
0042F4F7   84D2                   test    dl, dl
0042F4F9   7408                   jz      0042F503
0042F4FB   83C4F0                 add     esp, -$10

* Reference to: System.@ClassCreate(TClass;Boolean):TObject;
|
0042F4FE   E84942FDFF             call    0040374C
0042F503   8BF1                   mov     esi, ecx
0042F505   8BDA                   mov     ebx, edx
0042F507   8BF8                   mov     edi, eax
0042F509   33D2                   xor     edx, edx
0042F50B   8BC7                   mov     eax, edi

* Reference to: Graphics.TCanvas.Create(TCanvas;boolean);
|
0042F50D   E8E26BFFFF             call    004260F4
0042F512   897758                 mov     [edi+$58], esi
0042F515   8BC7                   mov     eax, edi
0042F517   84DB                   test    bl, bl
0042F519   740F                   jz      0042F52A

* Reference to: System.@AfterConstruction(TObject):TObject;
|
0042F51B   E88442FDFF             call    004037A4
0042F520   648F0500000000         pop     dword ptr fs:[$00000000]
0042F527   83C40C                 add     esp, +$0C
0042F52A   8BC7                   mov     eax, edi
0042F52C   5F                     pop     edi
0042F52D   5E                     pop     esi
0042F52E   5B                     pop     ebx
0042F52F   C3                     ret

*)
end;

procedure TPrinterCanvas._PROC_0043008C(Sender : TObject);
begin
(*
0043008C   833DD4D7490000         cmp     dword ptr [$0049D7D4], +$00
00430093   7511                   jnz     004300A6
00430095   B201                   mov     dl, $01

* Reference to class TPrinter
|
00430097   A1C8F14200             mov     eax, dword ptr [$0042F1C8]

* Reference to: Printers.TPrinter.Create(TPrinter;boolean);
|
0043009C   E81BF5FFFF             call    0042F5BC
004300A1   A3D4D74900             mov     dword ptr [$0049D7D4], eax
004300A6   A1D4D74900             mov     eax, dword ptr [$0049D7D4]
004300AB   C3                     ret

*)
end;

end.