unit unitform_logincode;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls
type
  Tform_logincode=class(TForm)
    btn_copy2clpbrd: TButton;
    OFFS_032C: N.A.;
    procedure FormCreate(Sender : TObject);
    procedure btn_copy2clpbrdClick(Sender : TObject);
    procedure _PROC_00499224(Sender : TObject);
    procedure _PROC_0049923C(Sender : TObject);
    procedure _PROC_00499240(Sender : TObject);
    procedure _PROC_004992B0(Sender : TObject);
    procedure _PROC_004992E0(Sender : TObject);
    procedure _PROC_004992E8(Sender : TObject);
    procedure _PROC_004993A6(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end ;

var
  form_logincode: Tform_logincode;

{This file is generated by DeDe Ver 3.50.04 Copyright (c) 1999-2002 DaFixer}

implementation

{$R *.DFM}

procedure Tform_logincode.FormCreate(Sender : TObject);
begin
(*
00499174   55                     push    ebp
00499175   8BEC                   mov     ebp, esp
00499177   6A00                   push    $00
00499179   53                     push    ebx
0049917A   8BD8                   mov     ebx, eax
0049917C   33C0                   xor     eax, eax
0049917E   55                     push    ebp

* Possible String Reference to: 'é´©öÿëð[Y]Ã‹ÀU‹ìj'
|
0049917F   68C3914900             push    $004991C3

***** TRY
|
00499184   64FF30                 push    dword ptr fs:[eax]
00499187   648920                 mov     fs:[eax], esp
0049918A   8D45FC                 lea     eax, [ebp-$04]

|
0049918D   E816DFFFFF             call    004970A8
00499192   8B55FC                 mov     edx, [ebp-$04]

* Reference to field Tform_logincode.OFFS_032C : String
|
00499195   8D832C030000           lea     eax, [ebx+$032C]

* Reference to: System.@LStrAsg(void;void;void;void);
|
0049919B   E82CB0F6FF             call    004041CC

* Reference to field Tform_logincode.OFFS_032C : String
|
004991A0   8B932C030000           mov     edx, [ebx+$032C]
004991A6   8BC3                   mov     eax, ebx

* Reference to: BrushDlg.TBrushDialog.FormClose(TBrushDialog;TObject;TCloseAction;TCloseAction);
|
004991A8   E853F6FFFF             call    00498800
004991AD   33C0                   xor     eax, eax
004991AF   5A                     pop     edx
004991B0   59                     pop     ecx
004991B1   59                     pop     ecx
004991B2   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '[Y]Ã‹ÀU‹ìj'
|
004991B5   68CA914900             push    $004991CA
004991BA   8D45FC                 lea     eax, [ebp-$04]

* Reference to: System.@LStrClr(void;void);
|
004991BD   E8B6AFF6FF             call    00404178
004991C2   C3                     ret


* Reference to: System.@HandleFinally;
|
004991C3   E9B4A9F6FF             jmp     00403B7C
004991C8   EBF0                   jmp     004991BA

****** END
|
004991CA   5B                     pop     ebx
004991CB   59                     pop     ecx
004991CC   5D                     pop     ebp
004991CD   C3                     ret

*)
end;

procedure Tform_logincode.btn_copy2clpbrdClick(Sender : TObject);
begin
(*
004991D0   55                     push    ebp
004991D1   8BEC                   mov     ebp, esp
004991D3   6A00                   push    $00
004991D5   53                     push    ebx
004991D6   8BD8                   mov     ebx, eax
004991D8   33C0                   xor     eax, eax
004991DA   55                     push    ebp
004991DB   6819924900             push    $00499219

***** TRY
|
004991E0   64FF30                 push    dword ptr fs:[eax]
004991E3   648920                 mov     fs:[eax], esp
004991E6   8D55FC                 lea     edx, [ebp-$04]

* Reference to field Tform_logincode.OFFS_030C
|
004991E9   8B830C030000           mov     eax, [ebx+$030C]

* Reference to: Controls.TControl.GetText(TControl):TCaption;
|
004991EF   E8ACF0FBFF             call    004582A0
004991F4   8B45FC                 mov     eax, [ebp-$04]
004991F7   50                     push    eax

* Reference to: Clipbrd.Clipboard:TClipboard;
|
004991F8   E8B7C8F9FF             call    00435AB4
004991FD   5A                     pop     edx

* Reference to: Clipbrd.TClipboard.SetAsText(TClipboard;AnsiString);
|
004991FE   E851C5F9FF             call    00435754
00499203   33C0                   xor     eax, eax
00499205   5A                     pop     edx
00499206   59                     pop     ecx
00499207   59                     pop     ecx
00499208   648910                 mov     fs:[eax], edx

****** FINALLY
|
0049920B   6820924900             push    $00499220
00499210   8D45FC                 lea     eax, [ebp-$04]

* Reference to: System.@LStrClr(void;void);
|
00499213   E860AFF6FF             call    00404178
00499218   C3                     ret


* Reference to: System.@HandleFinally;
|
00499219   E95EA9F6FF             jmp     00403B7C
0049921E   EBF0                   jmp     00499210

****** END
|
00499220   5B                     pop     ebx
00499221   59                     pop     ecx
00499222   5D                     pop     ebp
00499223   C3                     ret

*)
end;

procedure Tform_logincode._PROC_00499224(Sender : TObject);
begin
(*
00499224   53                     push    ebx
00499225   56                     push    esi
00499226   8BF2                   mov     esi, edx
00499228   8BD8                   mov     ebx, eax
0049922A   8BC6                   mov     eax, esi

* Reference to field Tform_logincode.OFFS_032C : String
|
0049922C   8B932C030000           mov     edx, [ebx+$032C]

* Reference to: System.@LStrAsg(void;void;void;void);
|
00499232   E895AFF6FF             call    004041CC
00499237   5E                     pop     esi
00499238   5B                     pop     ebx
00499239   C3                     ret

*)
end;

procedure Tform_logincode._PROC_0049923C(Sender : TObject);
begin
(*
0049923C   C3                     ret

*)
end;

procedure Tform_logincode._PROC_00499240(Sender : TObject);
begin
(*
00499240   53                     push    ebx
00499241   56                     push    esi
00499242   84D2                   test    dl, dl
00499244   7408                   jz      0049924E
00499246   83C4F0                 add     esp, -$10

* Reference to: System.@ClassCreate(TClass;Boolean):TObject;
|
00499249   E8FEA4F6FF             call    0040374C
0049924E   8BDA                   mov     ebx, edx
00499250   8BF0                   mov     esi, eax
00499252   33D2                   xor     edx, edx
00499254   8BC6                   mov     eax, esi

|
00499256   E869F6FFFF             call    004988C4
0049925B   8B15A8014A00           mov     edx, [$004A01A8]
00499261   8B12                   mov     edx, [edx]

* Reference to field Tform_logincode.OFFS_02FC
|
00499263   8B86FC020000           mov     eax, [esi+$02FC]

* Reference to: Controls.TControl.SetText(TControl;TCaption);
|
00499269   E862F0FBFF             call    004582D0
0049926E   8B1550014A00           mov     edx, [$004A0150]
00499274   8B12                   mov     edx, [edx]

* Reference to field Tform_logincode.OFFS_0300
|
00499276   8B8600030000           mov     eax, [esi+$0300]

* Reference to: Controls.TControl.SetText(TControl;TCaption);
|
0049927C   E84FF0FBFF             call    004582D0
00499281   8B15E0024A00           mov     edx, [$004A02E0]
00499287   8B12                   mov     edx, [edx]

* Reference to control Tform_logincode.btn_copy2clpbrd : TButton
|
00499289   8B8628030000           mov     eax, [esi+$0328]

* Reference to: Controls.TControl.SetText(TControl;TCaption);
|
0049928F   E83CF0FBFF             call    004582D0
00499294   8BC6                   mov     eax, esi
00499296   84DB                   test    bl, bl
00499298   740F                   jz      004992A9

* Reference to: System.@AfterConstruction(TObject):TObject;
|
0049929A   E805A5F6FF             call    004037A4
0049929F   648F0500000000         pop     dword ptr fs:[$00000000]
004992A6   83C40C                 add     esp, +$0C
004992A9   8BC6                   mov     eax, esi
004992AB   5E                     pop     esi
004992AC   5B                     pop     ebx
004992AD   C3                     ret

*)
end;

procedure Tform_logincode._PROC_004992B0(Sender : TObject);
begin
(*
004992B0   55                     push    ebp
004992B1   8BEC                   mov     ebp, esp
004992B3   33C0                   xor     eax, eax
004992B5   55                     push    ebp
004992B6   68D5924900             push    $004992D5

***** TRY
|
004992BB   64FF30                 push    dword ptr fs:[eax]
004992BE   648920                 mov     fs:[eax], esp
004992C1   FF052C1E4A00           inc     dword ptr [$004A1E2C]
004992C7   33C0                   xor     eax, eax
004992C9   5A                     pop     edx
004992CA   59                     pop     ecx
004992CB   59                     pop     ecx
004992CC   648910                 mov     fs:[eax], edx

****** FINALLY
|
004992CF   68DC924900             push    $004992DC
004992D4   C3                     ret


* Reference to: System.@HandleFinally;
|
004992D5   E9A2A8F6FF             jmp     00403B7C
004992DA   EBF8                   jmp     004992D4

****** END
|
004992DC   5D                     pop     ebp
004992DD   C3                     ret

*)
end;

procedure Tform_logincode._PROC_004992E0(Sender : TObject);
begin
(*
004992E0   832D2C1E4A0001         sub     dword ptr [$004A1E2C], +$01
004992E7   C3                     ret

*)
end;

procedure Tform_logincode._PROC_004992E8(Sender : TObject);
begin
(*
004992E8   3493                   xor     al, $93
004992EA   49                     dec     ecx
004992EB   0000                   add     [eax], al

*)
end;

procedure Tform_logincode._PROC_004993A6(Sender : TObject);
begin
(*
004993A6   45                     inc     ebp
004993A7   0034154700DCA5         add     [$A5DC0047+edx], dh
004993AE   45                     inc     ebp
004993AF   00F4                   add     ah, dh
004993B1   E84500B0E9             call    E9F993FB
004993B6   45                     inc     ebp
004993B7   0074E445               add     [esp+$45], dh
004993BB   0094E94500CC04         add     [ecx+ebp*8+$4CC0045], dl
004993C2   47                     inc     edi
004993C3   00D8                   add     al, bl
004993C5   1B4700                 sbb     eax, [edi+$00]
004993C8   28BF45009C28           sub     [edi+$289C0045], bh
004993CE   47                     inc     edi
004993CF   00FC                   add     ah, bh
004993D1   2B4700                 sub     eax, dword ptr [edi+$00]
004993D4   B82A4700C0             mov     eax, $C000472A
004993D9   BF4500C4BF             mov     edi, $BFC40045
004993DE   45                     inc     ebp
004993DF   00342D470024BE         add     [$BE240047+ebp], dh
004993E6   45                     inc     ebp
004993E7   00D4                   add     ah, dl
004993E9   EA45002834             jmp     $34280045
004993EE   47                     inc     edi
004993EF   0084FC450018E7         add     [esp+edi*8+$E7180045], al
004993F6   45                     inc     ebp
004993F7   003C49                 add     [ecx+ecx*2], bh
004993FA   47                     inc     edi
004993FB   00C0                   add     al, al
004993FD   FE4600                 inc     byte ptr [esi+$00]
00499400   7001                   jo      00499403
00499402   47                     inc     edi
00499403   001C3A                 add     [edx+edi], bl
00499406   47                     inc     edi
00499407   00580A                 add     [eax+$0A], bl
0049940A   47                     inc     edi
0049940B   00D4                   add     ah, dl
0049940D   0A4700                 or      al, byte ptr [edi+$00]
00499410   1C4D                   sbb     al, $4D
00499412   47                     inc     edi
00499413   009007470020           add     [eax+$20004707], dl
00499419   48                     dec     eax
0049941A   47                     inc     edi
0049941B   0000                   add     [eax], al

*)
end;

end.