unit unitform_demomsg;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls
type
  Tform_demomsg=class(TForm)
    Timer: TTimer;
    pnl_main: TPanel;
    btnOk: TButton;
    Label1: TLabel;
    lblHyperlink: TLabel;
    procedure btnOkClick(Sender : TObject);
    procedure TimerTimer(Sender : TObject);
    procedure FormCloseQuery(Sender : TObject);
    procedure lblHyperlinkClick(Sender : TObject);
    procedure _PROC_00496DC1(Sender : TObject);
    procedure _PROC_00496DF0(Sender : TObject);
    procedure _PROC_00496DF8(Sender : TObject);
    procedure _PROC_00496EA1(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end ;

var
  form_demomsg: Tform_demomsg;

{This file is generated by DeDe Ver 3.50.04 Copyright (c) 1999-2002 DaFixer}

implementation

{$R *.DFM}

procedure Tform_demomsg.btnOkClick(Sender : TObject);
begin
(*

* Reference to: Forms.TCustomForm.Close(TCustomForm);
|
00496D1C   E85BDAFDFF             call    0047477C
00496D21   C3                     ret

*)
end;

procedure Tform_demomsg.TimerTimer(Sender : TObject);
begin
(*
00496D40   53                     push    ebx
00496D41   8BD8                   mov     ebx, eax
00496D43   33D2                   xor     edx, edx

* Reference to control Tform_demomsg.Timer : TTimer
|
00496D45   8B83F8020000           mov     eax, [ebx+$02F8]

* Reference to: ExtCtrls.TTimer.SetEnabled(TTimer;Boolean);
|
00496D4B   E8ACDCF9FF             call    004349FC
00496D50   B201                   mov     dl, $01

* Reference to control Tform_demomsg.btnOk : TButton
|
00496D52   8B8300030000           mov     eax, [ebx+$0300]
00496D58   8B08                   mov     ecx, [eax]

* Reference to method TButton.SetEnabled(Boolean)
|
00496D5A   FF5164                 call    dword ptr [ecx+$64]

* Reference to field Tform_demomsg.Tag : Longint
|
00496D5D   C7430C01000000         mov     dword ptr [ebx+$0C], $00000001
00496D64   5B                     pop     ebx
00496D65   C3                     ret

*)
end;

procedure Tform_demomsg.FormCloseQuery(Sender : TObject);
begin
(*

* Reference to control Tform_demomsg.Timer : TTimer
|
00496D68   8B90F8020000           mov     edx, [eax+$02F8]

* Reference to field TTimer.Enabled : Boolean
|
00496D6E   807A4000               cmp     byte ptr [edx+$40], $00
00496D72   7506                   jnz     00496D7A

* Reference to field Tform_demomsg.Tag : Longint
|
00496D74   83780C01               cmp     dword ptr [eax+$0C], +$01
00496D78   7405                   jz      00496D7F
00496D7A   33C0                   xor     eax, eax
00496D7C   8801                   mov     [ecx], al
00496D7E   C3                     ret

00496D7F   B001                   mov     al, $01
00496D81   8801                   mov     [ecx], al
00496D83   C3                     ret

*)
end;

procedure Tform_demomsg.lblHyperlinkClick(Sender : TObject);
begin
(*

* Possible String Reference to: 'http://link.ebookedit.com/d/go.cgi?
|                                demo'
|
00496D84   B8986D4900             mov     eax, $00496D98

* Reference to : TRzBitBtn._PROC_0048F168()
|
00496D89   E8DA83FFFF             call    0048F168
00496D8E   C3                     ret

*)
end;

procedure Tform_demomsg._PROC_00496DC1(Sender : TObject);
begin
(*
00496DC1   8BEC                   mov     ebp, esp
00496DC3   33C0                   xor     eax, eax
00496DC5   55                     push    ebp
00496DC6   68E56D4900             push    $00496DE5

***** TRY
|
00496DCB   64FF30                 push    dword ptr fs:[eax]
00496DCE   648920                 mov     fs:[eax], esp
00496DD1   FF050C1E4A00           inc     dword ptr [$004A1E0C]
00496DD7   33C0                   xor     eax, eax
00496DD9   5A                     pop     edx
00496DDA   59                     pop     ecx
00496DDB   59                     pop     ecx
00496DDC   648910                 mov     fs:[eax], edx

****** FINALLY
|
00496DDF   68EC6D4900             push    $00496DEC
00496DE4   C3                     ret


* Reference to: System.@HandleFinally;
|
00496DE5   E992CDF6FF             jmp     00403B7C
00496DEA   EBF8                   jmp     00496DE4

****** END
|
00496DEC   5D                     pop     ebp
00496DED   C3                     ret

*)
end;

procedure Tform_demomsg._PROC_00496DF0(Sender : TObject);
begin
(*
00496DF0   832D0C1E4A0001         sub     dword ptr [$004A1E0C], +$01
00496DF7   C3                     ret

*)
end;

procedure Tform_demomsg._PROC_00496DF8(Sender : TObject);
begin
(*
00496DF8   44                     inc     esp
00496DF9   6E                     outsb
00496DFA   49                     dec     ecx
00496DFB   0000                   add     [eax], al

*)
end;

procedure Tform_demomsg._PROC_00496EA1(Sender : TObject);
begin
(*
00496EA1   52                     push    edx
00496EA2   4C                     dec     esp
00496EA3   4D                     dec     ebp
00496EA4   656E                   outsb
00496EA6   7549                   jnz     00496EF1
00496EA8   7465                   jz      00496F0F
00496EAA   6D                     insd
00496EAB   90                     nop
00496EAC   B06E                   mov     al, $6E
00496EAE   49                     dec     ecx
00496EAF   0007                   add     [edi], al
00496EB1   0C54                   or      al, $54
00496EB3   55                     push    ebp
00496EB4   52                     push    edx
00496EB5   4C                     dec     esp
00496EB6   4D                     dec     ebp
00496EB7   656E                   outsb
00496EB9   7549                   jnz     00496F04
00496EBB   7465                   jz      00496F22
00496EBD   6D                     insd
00496EBE   44                     inc     esp
00496EBF   6E                     outsb
00496EC0   49                     dec     ecx
00496EC1   00846C46001800         add     [esp+ebp*2+$180046], al
00496EC8   10756E                 adc     [ebp+$6E], dh
00496ECB   69745F75726C6D65       imul    esi, [edi+ebx*2+$75], $656D6C72
00496ED3   6E                     outsb
00496ED4   7569                   jnz     00496F3F
00496ED6   7465                   jz      00496F3D
00496ED8   6D                     insd
00496ED9   0000                   add     [eax], al

00496EDB   90                     nop
00496EDC   53                     push    ebx
00496EDD   56                     push    esi
00496EDE   84D2                   test    dl, dl
00496EE0   7408                   jz      00496EEA
00496EE2   83C4F0                 add     esp, -$10

* Reference to: System.@ClassCreate(TClass;Boolean):TObject;
|
00496EE5   E862C8F6FF             call    0040374C
00496EEA   8BDA                   mov     ebx, edx
00496EEC   8BF0                   mov     esi, eax
00496EEE   33D2                   xor     edx, edx
00496EF0   8BC6                   mov     eax, esi

* Reference to: Menus.TMenuItem.Create(TMenuItem;boolean;TComponent);
|
00496EF2   E89D11FDFF             call    00468094
00496EF7   89B68C000000           mov     [esi+$008C], esi
00496EFD   C786880000004C6F4900   mov     dword ptr [esi+$0088], $00496F4C
00496F07   8BC6                   mov     eax, esi
00496F09   84DB                   test    bl, bl
00496F0B   740F                   jz      00496F1C

* Reference to: System.@AfterConstruction(TObject):TObject;
|
00496F0D   E892C8F6FF             call    004037A4
00496F12   648F0500000000         pop     dword ptr fs:[$00000000]
00496F19   83C40C                 add     esp, +$0C
00496F1C   8BC6                   mov     eax, esi
00496F1E   5E                     pop     esi
00496F1F   5B                     pop     ebx
00496F20   C3                     ret

00496F21   8D4000                 lea     eax, [eax+$00]
00496F24   53                     push    ebx
00496F25   56                     push    esi

* Reference to: System.@BeforeDestruction(TObject;Shortint):TObject;
|
00496F26   E889C8F6FF             call    004037B4
00496F2B   8BDA                   mov     ebx, edx
00496F2D   8BF0                   mov     esi, eax
00496F2F   8BD3                   mov     edx, ebx
00496F31   80E2FC                 and     dl, $FC
00496F34   8BC6                   mov     eax, esi

* Reference to: Menus.TMenuItem.Destroy(TMenuItem;boolean);
|
00496F36   E8D511FDFF             call    00468110
00496F3B   84DB                   test    bl, bl
00496F3D   7E07                   jle     00496F46
00496F3F   8BC6                   mov     eax, esi

* Reference to: System.@ClassDestroy(TObject);
|
00496F41   E856C8F6FF             call    0040379C
00496F46   5E                     pop     esi
00496F47   5B                     pop     ebx
00496F48   C3                     ret

*)
end;

end.