unit unitform_about;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls
type
  Tform_about=class(TForm)
    panel_top: TPanel;
    panel_bottom: TPanel;
    image_logo: TImage;
    label_product: TLabel;
    label_producturl: TLabel;
    Label1: TLabel;
    Label2: TLabel;
    Label3: TLabel;
    RzButton1: TRzButton;
    memo_customtext: TRichEdit;
    OFFS_0324: N.A.;
    procedure URLClick(Sender : TObject);
    procedure FormShow(Sender : TObject);
    procedure URLRegUserClick(Sender : TObject);
    procedure FormKeyDown(Sender : TObject);
    procedure _PROC_0049669A(Sender : TObject);
    procedure _PROC_004966A9(Sender : TObject);
    procedure _PROC_00496764(Sender : TObject);
    procedure _PROC_00496780(Sender : TObject);
    procedure _PROC_004967B4(Sender : TObject);
    procedure _PROC_00496AB5(Sender : TObject);
    procedure _PROC_00496AE4(Sender : TObject);
    procedure _PROC_00496AEC(Sender : TObject);
    procedure _PROC_00496BAA(Sender : TObject);
    procedure _PROC_00496690(Sender : TObject);
    procedure _PROC_00496684(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end ;

var
  form_about: Tform_about;

{This file is generated by DeDe Ver 3.50.04 Copyright (c) 1999-2002 DaFixer}

implementation

{$R *.DFM}

procedure Tform_about.URLClick(Sender : TObject);
begin
(*
00496544   55                     push    ebp
00496545   8BEC                   mov     ebp, esp
00496547   83C4F4                 add     esp, -$0C
0049654A   33C9                   xor     ecx, ecx
0049654C   894DFC                 mov     [ebp-$04], ecx
0049654F   33C0                   xor     eax, eax
00496551   55                     push    ebp

* Possible String Reference to: 'È€’ˆˇÎãÂ]√'
|
00496552   689C654900             push    $0049659C

***** TRY
|
00496557   64FF30                 push    dword ptr fs:[eax]
0049655A   648920                 mov     fs:[eax], esp
0049655D   8D45FC                 lea     eax, [ebp-$04]
00496560   50                     push    eax

* Reference to pointer to GlobalVar_004A1D74
|
00496561   A158FF4900             mov     eax, dword ptr [$0049FF58]
00496566   8B00                   mov     eax, [eax]
00496568   8945F4                 mov     [ebp-$0C], eax
0049656B   C645F80B               mov     byte ptr [ebp-$08], $0B
0049656F   8D55F4                 lea     edx, [ebp-$0C]
00496572   33C9                   xor     ecx, ecx

* Possible String Reference to: 'http://refer.ebookedit.com/click.cg
|                                i?id=%s'
|
00496574   B8B0654900             mov     eax, $004965B0

|
00496579   E83233F7FF             call    004098B0
0049657E   8B45FC                 mov     eax, [ebp-$04]

* Reference to : TRzBitBtn._PROC_0048F168()
|
00496581   E8E28BFFFF             call    0048F168
00496586   33C0                   xor     eax, eax
00496588   5A                     pop     edx
00496589   59                     pop     ecx
0049658A   59                     pop     ecx
0049658B   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: 'ãÂ]√'
|
0049658E   68A3654900             push    $004965A3
00496593   8D45FC                 lea     eax, [ebp-$04]

* Reference to: System.@LStrClr(void;void);
|
00496596   E8DDDBF6FF             call    00404178
0049659B   C3                     ret


* Reference to: System.@HandleFinally;
|
0049659C   E9DBD5F6FF             jmp     00403B7C
004965A1   EBF0                   jmp     00496593

****** END
|
004965A3   8BE5                   mov     esp, ebp
004965A5   5D                     pop     ebp
004965A6   C3                     ret

*)
end;

procedure Tform_about.FormShow(Sender : TObject);
begin
(*
004965DC   55                     push    ebp
004965DD   8BEC                   mov     ebp, esp
004965DF   6A00                   push    $00
004965E1   6A00                   push    $00
004965E3   53                     push    ebx
004965E4   8BD8                   mov     ebx, eax
004965E6   33C0                   xor     eax, eax
004965E8   55                     push    ebp
004965E9   6860664900             push    $00496660

***** TRY
|
004965EE   64FF30                 push    dword ptr fs:[eax]
004965F1   648920                 mov     fs:[eax], esp
004965F4   8D55FC                 lea     edx, [ebp-$04]
004965F7   8BC3                   mov     eax, ebx

* Reference to: QComCtrls.TToolBar.GetControl(TToolBar;Integer):TControl;
|
004965F9   E892000000             call    00496690
004965FE   837DFC00               cmp     dword ptr [ebp-$04], +$00
00496602   750C                   jnz     00496610

* Possible String Reference to: 'Œ¥◊¢≤·∞Ê±æ'
|
00496604   BA74664900             mov     edx, $00496674
00496609   8BC3                   mov     eax, ebx

|
0049660B   E898000000             call    004966A8
00496610   8D55F8                 lea     edx, [ebp-$08]
00496613   8BC3                   mov     eax, ebx

* Reference to : Tform_about._PROC_00496764()
|
00496615   E84A010000             call    00496764
0049661A   837DF800               cmp     dword ptr [ebp-$08], +$00
0049661E   0F95C2                 setnz   dl

* Reference to control Tform_about.memo_customtext : TRichEdit
|
00496621   8B831C030000           mov     eax, [ebx+$031C]

* Reference to: Controls.TControl.SetVisible(TControl;Boolean);
|
00496627   E8941BFCFF             call    004581C0

* Reference to control Tform_about.memo_customtext : TRichEdit
|
0049662C   8B831C030000           mov     eax, [ebx+$031C]

* Reference to field TRichEdit.Visible : Boolean
|
00496632   80785700               cmp     byte ptr [eax+$57], $00
00496636   750D                   jnz     00496645

* Reference to field Tform_about.Height : Integer
|
00496638   8B534C                 mov     edx, [ebx+$4C]
0049663B   2B504C                 sub     edx, dword ptr [eax+$4C]
0049663E   8BC3                   mov     eax, ebx

* Reference to: Controls.TControl.SetHeight(TControl;Integer);
|
00496640   E81314FCFF             call    00457A58
00496645   33C0                   xor     eax, eax
00496647   5A                     pop     edx
00496648   59                     pop     ecx
00496649   59                     pop     ecx
0049664A   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '[YY]√ˇˇˇˇ'
|
0049664D   6867664900             push    $00496667
00496652   8D45F8                 lea     eax, [ebp-$08]
00496655   BA02000000             mov     edx, $00000002

* Reference to: System.@LStrArrayClr(void;void;Integer);
|
0049665A   E83DDBF6FF             call    0040419C
0049665F   C3                     ret


* Reference to: System.@HandleFinally;
|
00496660   E917D5F6FF             jmp     00403B7C
00496665   EBEB                   jmp     00496652

****** END
|
00496667   5B                     pop     ebx
00496668   59                     pop     ecx
00496669   59                     pop     ecx
0049666A   5D                     pop     ebp
0049666B   C3                     ret

*)
end;

procedure Tform_about.URLRegUserClick(Sender : TObject);
begin
(*
004966FC   55                     push    ebp
004966FD   8BEC                   mov     ebp, esp
004966FF   6A00                   push    $00
00496701   53                     push    ebx
00496702   8BDA                   mov     ebx, edx
00496704   33C0                   xor     eax, eax
00496706   55                     push    ebp

* Possible String Reference to: 'È!‘ˆˇÎ[Y]√ç@'
|
00496707   6856674900             push    $00496756

***** TRY
|
0049670C   64FF30                 push    dword ptr fs:[eax]
0049670F   648920                 mov     fs:[eax], esp
00496712   8BC3                   mov     eax, ebx

* Reference to class TLabel
|
00496714   8B151CCE4400           mov     edx, [$0044CE1C]

* Reference to: System.@IsClass(TObject;TClass):Boolean;
|
0049671A   E855CEF6FF             call    00403574
0049671F   84C0                   test    al, al
00496721   741D                   jz      00496740
00496723   8BC3                   mov     eax, ebx

* Reference to class TLabel
|
00496725   8B151CCE4400           mov     edx, [$0044CE1C]

* Reference to: System.@AsClass(TObject;TClass):TObject;
|
0049672B   E868CEF6FF             call    00403598
00496730   8D55FC                 lea     edx, [ebp-$04]

* Reference to: Controls.TControl.GetText(TControl):TCaption;
|
00496733   E8681BFCFF             call    004582A0
00496738   8B45FC                 mov     eax, [ebp-$04]

* Reference to : TRzBitBtn._PROC_0048F168()
|
0049673B   E8288AFFFF             call    0048F168
00496740   33C0                   xor     eax, eax
00496742   5A                     pop     edx
00496743   59                     pop     ecx
00496744   59                     pop     ecx
00496745   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '[Y]√ç@'
|
00496748   685D674900             push    $0049675D
0049674D   8D45FC                 lea     eax, [ebp-$04]

* Reference to: System.@LStrClr(void;void);
|
00496750   E823DAF6FF             call    00404178
00496755   C3                     ret


* Reference to: System.@HandleFinally;
|
00496756   E921D4F6FF             jmp     00403B7C
0049675B   EBF0                   jmp     0049674D

****** END
|
0049675D   5B                     pop     ebx
0049675E   59                     pop     ecx
0049675F   5D                     pop     ebp
00496760   C3                     ret

*)
end;

procedure Tform_about.FormKeyDown(Sender : TObject);
begin
(*
00496848   55                     push    ebp
00496849   8BEC                   mov     ebp, esp
0049684B   51                     push    ecx
0049684C   B905000000             mov     ecx, $00000005
00496851   6A00                   push    $00
00496853   6A00                   push    $00
00496855   49                     dec     ecx
00496856   75F9                   jnz     00496851
00496858   51                     push    ecx
00496859   874DFC                 xchg    [ebp-$04], ecx
0049685C   53                     push    ebx
0049685D   56                     push    esi
0049685E   8BF1                   mov     esi, ecx
00496860   8BD8                   mov     ebx, eax
00496862   33C0                   xor     eax, eax
00496864   55                     push    ebp
00496865   68F2694900             push    $004969F2

***** TRY
|
0049686A   64FF30                 push    dword ptr fs:[eax]
0049686D   648920                 mov     fs:[eax], esp
00496870   F6450802               test    byte ptr [ebp+$08], $02
00496874   0F845D010000           jz      004969D7
0049687A   F606FF                 test    byte ptr [esi], $FF
0049687D   0F8454010000           jz      004969D7
00496883   8D45FC                 lea     eax, [ebp-$04]
00496886   668B16                 mov     dx, word ptr [esi]
00496889   80E2FF                 and     dl, $FF

* Reference to: System.@LStrFromChar(String;String;Char);
|
0049688C   E8CFDAF6FF             call    00404360
00496891   8B55FC                 mov     edx, [ebp-$04]

* Reference to field Tform_about.OFFS_0324 : String
|
00496894   8D8324030000           lea     eax, [ebx+$0324]

* Reference to: System.@LStrCat;
|
0049689A   E8A1DBF6FF             call    00404440
0049689F   8D55F8                 lea     edx, [ebp-$08]

* Reference to field Tform_about.OFFS_0324 : String
|
004968A2   8B8324030000           mov     eax, [ebx+$0324]

* Reference to: SysUtils.UpperCase(AnsiString):AnsiString;
|
004968A8   E8B71BF7FF             call    00408464
004968AD   8B55F8                 mov     edx, [ebp-$08]

* Reference to field Tform_about.OFFS_0324 : String
|
004968B0   8D8324030000           lea     eax, [ebx+$0324]

* Reference to: System.@LStrAsg(void;void;void;void);
|
004968B6   E811D9F6FF             call    004041CC

* Possible String Reference to: 'DATE'
|
004968BB   BA0C6A4900             mov     edx, $00496A0C

* Reference to field Tform_about.OFFS_0324 : String
|
004968C0   8B8324030000           mov     eax, [ebx+$0324]

* Reference to : Tform_about._PROC_004967B4()
|
004968C6   E8E9FEFFFF             call    004967B4
004968CB   84C0                   test    al, al
004968CD   7546                   jnz     00496915

* Possible String Reference to: 'CODE'
|
004968CF   BA1C6A4900             mov     edx, $00496A1C

* Reference to field Tform_about.OFFS_0324 : String
|
004968D4   8B8324030000           mov     eax, [ebx+$0324]

* Reference to : Tform_about._PROC_004967B4()
|
004968DA   E8D5FEFFFF             call    004967B4
004968DF   84C0                   test    al, al
004968E1   7532                   jnz     00496915

* Possible String Reference to: 'VERSION'
|
004968E3   BA2C6A4900             mov     edx, $00496A2C

* Reference to field Tform_about.OFFS_0324 : String
|
004968E8   8B8324030000           mov     eax, [ebx+$0324]

* Reference to : Tform_about._PROC_004967B4()
|
004968EE   E8C1FEFFFF             call    004967B4
004968F3   84C0                   test    al, al
004968F5   751E                   jnz     00496915

* Reference to field Tform_about.OFFS_0324 : String
|
004968F7   8B8324030000           mov     eax, [ebx+$0324]

* Reference to: System.@LStrLen(String):Integer;
|
004968FD   E836DBF6FF             call    00404438
00496902   8BC8                   mov     ecx, eax
00496904   49                     dec     ecx

* Reference to field Tform_about.OFFS_0324 : String
|
00496905   8D8324030000           lea     eax, [ebx+$0324]
0049690B   BA01000000             mov     edx, $00000001

* Reference to: System.@LStrDelete;
|
00496910   E8C3DDF6FF             call    004046D8

* Reference to field Tform_about.OFFS_0324 : String
|
00496915   8B8324030000           mov     eax, [ebx+$0324]

* Possible String Reference to: 'DATE'
|
0049691B   BA0C6A4900             mov     edx, $00496A0C

* Reference to: System.@LStrCmp;
|
00496920   E85FDCF6FF             call    00404584
00496925   7531                   jnz     00496958

* Reference to pointer to GlobalVar_004A1D58
|
00496927   A178034A00             mov     eax, dword ptr [$004A0378]
0049692C   FF7004                 push    dword ptr [eax+$04]
0049692F   FF30                   push    dword ptr [eax]
00496931   8D55F0                 lea     edx, [ebp-$10]

* Possible String Reference to: 'yyyy, mmmm d, dddd, hh:mm'
|
00496934   B83C6A4900             mov     eax, $00496A3C

|
00496939   E82E48F7FF             call    0040B16C
0049693E   8B4DF0                 mov     ecx, [ebp-$10]
00496941   8D45F4                 lea     eax, [ebp-$0C]

* Possible String Reference to: 'µÁ◊” È¥¥Ω®”⁄£∫'
|
00496944   BA606A4900             mov     edx, $00496A60

* Reference to: System.@LStrCat3;
|
00496949   E836DBF6FF             call    00404484
0049694E   8B45F4                 mov     eax, [ebp-$0C]

* Reference to: Dialogs.ShowMessage(AnsiString);
|
00496951   E8E6C4F9FF             call    00432E3C
00496956   EB7F                   jmp     004969D7

* Reference to field Tform_about.OFFS_0324 : String
|
00496958   8B8324030000           mov     eax, [ebx+$0324]

* Possible String Reference to: 'CODE'
|
0049695E   BA1C6A4900             mov     edx, $00496A1C

* Reference to: System.@LStrCmp;
|
00496963   E81CDCF6FF             call    00404584
00496968   752B                   jnz     00496995
0049696A   8D4DE8                 lea     ecx, [ebp-$18]

* Reference to pointer to GlobalVar_004A1D54
|
0049696D   A124FF4900             mov     eax, dword ptr [$0049FF24]
00496972   8B00                   mov     eax, [eax]
00496974   33D2                   xor     edx, edx

* Reference to: SysUtils.IntToHex(Integer;Integer):AnsiString;overload;
|
00496976   E8B520F7FF             call    00408A30
0049697B   8B4DE8                 mov     ecx, [ebp-$18]
0049697E   8D45EC                 lea     eax, [ebp-$14]

* Possible String Reference to: 'Œ®“ªµƒµÁ◊” È¥˙¬Î£∫ '
|
00496981   BA7C6A4900             mov     edx, $00496A7C

* Reference to: System.@LStrCat3;
|
00496986   E8F9DAF6FF             call    00404484
0049698B   8B45EC                 mov     eax, [ebp-$14]

* Reference to: Dialogs.ShowMessage(AnsiString);
|
0049698E   E8A9C4F9FF             call    00432E3C
00496993   EB42                   jmp     004969D7

* Reference to field Tform_about.OFFS_0324 : String
|
00496995   8B8324030000           mov     eax, [ebx+$0324]

* Possible String Reference to: 'VERSION'
|
0049699B   BA2C6A4900             mov     edx, $00496A2C

* Reference to: System.@LStrCmp;
|
004969A0   E8DFDBF6FF             call    00404584
004969A5   7530                   jnz     004969D7
004969A7   8D45E4                 lea     eax, [ebp-$1C]
004969AA   50                     push    eax
004969AB   A198014A00             mov     eax, dword ptr [$004A0198]
004969B0   DD00                   fld     qword ptr [eax]
004969B2   DB7DD0                 fstp    tbyte ptr [ebp-$30]
004969B5   9B                     wait
004969B6   8D45D0                 lea     eax, [ebp-$30]
004969B9   8945DC                 mov     [ebp-$24], eax
004969BC   C645E003               mov     byte ptr [ebp-$20], $03
004969C0   8D55DC                 lea     edx, [ebp-$24]
004969C3   33C9                   xor     ecx, ecx

* Possible String Reference to: 'Compiled with version %.2f'
|
004969C5   B8986A4900             mov     eax, $00496A98

|
004969CA   E8E12EF7FF             call    004098B0
004969CF   8B45E4                 mov     eax, [ebp-$1C]

* Reference to: Dialogs.ShowMessage(AnsiString);
|
004969D2   E865C4F9FF             call    00432E3C
004969D7   33C0                   xor     eax, eax
004969D9   5A                     pop     edx
004969DA   59                     pop     ecx
004969DB   59                     pop     ecx
004969DC   648910                 mov     fs:[eax], edx

****** FINALLY
|
004969DF   68F9694900             push    $004969F9
004969E4   8D45E4                 lea     eax, [ebp-$1C]
004969E7   BA07000000             mov     edx, $00000007

* Reference to: System.@LStrArrayClr(void;void;Integer);
|
004969EC   E8ABD7F6FF             call    0040419C
004969F1   C3                     ret


* Reference to: System.@HandleFinally;
|
004969F2   E985D1F6FF             jmp     00403B7C
004969F7   EBEB                   jmp     004969E4

****** END
|
004969F9   5E                     pop     esi
004969FA   5B                     pop     ebx
004969FB   8BE5                   mov     esp, ebp
004969FD   5D                     pop     ebp
004969FE   C20400                 ret     $0004

*)
end;

procedure Tform_about._PROC_0049669A(Sender : TObject);
begin
(*
0049669A   1003                   adc     [ebx], al
0049669C   0000                   add     [eax], al

*)
end;

procedure Tform_about._PROC_004966A9(Sender : TObject);
begin
(*
004966A9   8BEC                   mov     ebp, esp
004966AB   6A00                   push    $00
004966AD   53                     push    ebx
004966AE   56                     push    esi
004966AF   8BF2                   mov     esi, edx
004966B1   8BD8                   mov     ebx, eax
004966B3   33C0                   xor     eax, eax
004966B5   55                     push    ebp

* Possible String Reference to: 'Èà‘ˆˇÎ^[Y]√êUãÏj'
|
004966B6   68EF664900             push    $004966EF

***** TRY
|
004966BB   64FF30                 push    dword ptr fs:[eax]
004966BE   648920                 mov     fs:[eax], esp
004966C1   8D55FC                 lea     edx, [ebp-$04]
004966C4   8BC6                   mov     eax, esi

|
004966C6   E8318CFFFF             call    0048F2FC
004966CB   8B55FC                 mov     edx, [ebp-$04]

* Reference to control Tform_about.Label2 : TLabel
|
004966CE   8B8310030000           mov     eax, [ebx+$0310]

* Reference to: Controls.TControl.SetText(TControl;TCaption);
|
004966D4   E8F71BFCFF             call    004582D0
004966D9   33C0                   xor     eax, eax
004966DB   5A                     pop     edx
004966DC   59                     pop     ecx
004966DD   59                     pop     ecx
004966DE   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '^[Y]√êUãÏj'
|
004966E1   68F6664900             push    $004966F6
004966E6   8D45FC                 lea     eax, [ebp-$04]

* Reference to: System.@LStrClr(void;void);
|
004966E9   E88ADAF6FF             call    00404178
004966EE   C3                     ret


* Reference to: System.@HandleFinally;
|
004966EF   E988D4F6FF             jmp     00403B7C
004966F4   EBF0                   jmp     004966E6

****** END
|
004966F6   5E                     pop     esi
004966F7   5B                     pop     ebx
004966F8   59                     pop     ecx
004966F9   5D                     pop     ebp
004966FA   C3                     ret

*)
end;

procedure Tform_about._PROC_00496764(Sender : TObject);
begin
(*
00496764   53                     push    ebx
00496765   56                     push    esi
00496766   8BF2                   mov     esi, edx
00496768   8BD8                   mov     ebx, eax
0049676A   8BD6                   mov     edx, esi

* Reference to control Tform_about.memo_customtext : TRichEdit
|
0049676C   8B831C030000           mov     eax, [ebx+$031C]

* Reference to field TRichEdit.Lines : TStrings
|
00496772   8B8048020000           mov     eax, [eax+$0248]
00496778   8B08                   mov     ecx, [eax]

* Reference to method TStrings.GetTextStr()
|
0049677A   FF511C                 call    dword ptr [ecx+$1C]
0049677D   5E                     pop     esi
0049677E   5B                     pop     ebx
0049677F   C3                     ret

*)
end;

procedure Tform_about._PROC_00496780(Sender : TObject);
begin
(*
00496780   53                     push    ebx
00496781   8BD8                   mov     ebx, eax

* Reference to control Tform_about.memo_customtext : TRichEdit
|
00496783   8B831C030000           mov     eax, [ebx+$031C]

* Reference to field TRichEdit.Lines : TStrings
|
00496789   8B8048020000           mov     eax, [eax+$0248]
0049678F   8B08                   mov     ecx, [eax]

* Reference to method TStrings.SetTextStr(string)
|
00496791   FF512C                 call    dword ptr [ecx+$2C]
00496794   33D2                   xor     edx, edx

* Reference to control Tform_about.memo_customtext : TRichEdit
|
00496796   8B831C030000           mov     eax, [ebx+$031C]
0049679C   8B08                   mov     ecx, [eax]

* Reference to method TRichEdit.SetSelStart(Integer)
|
0049679E   FF91DC000000           call    dword ptr [ecx+$00DC]

* Reference to control Tform_about.memo_customtext : TRichEdit
|
004967A4   8B931C030000           mov     edx, [ebx+$031C]
004967AA   8BC3                   mov     eax, ebx

* Reference to: Forms.TCustomForm.SetActiveControl(TCustomForm;TWinControl);
|
004967AC   E82BC6FDFF             call    00472DDC
004967B1   5B                     pop     ebx
004967B2   C3                     ret

*)
end;

procedure Tform_about._PROC_004967B4(Sender : TObject);
begin
(*
004967B4   55                     push    ebp
004967B5   8BEC                   mov     ebp, esp
004967B7   83C4F0                 add     esp, -$10
004967BA   53                     push    ebx
004967BB   33C9                   xor     ecx, ecx
004967BD   894DF4                 mov     [ebp-$0C], ecx
004967C0   894DF0                 mov     [ebp-$10], ecx
004967C3   8955F8                 mov     [ebp-$08], edx
004967C6   8945FC                 mov     [ebp-$04], eax
004967C9   8B45FC                 mov     eax, [ebp-$04]

* Reference to: System.@LStrAddRef(void;void):Pointer;
|
004967CC   E857DEF6FF             call    00404628
004967D1   8B45F8                 mov     eax, [ebp-$08]

* Reference to: System.@LStrAddRef(void;void):Pointer;
|
004967D4   E84FDEF6FF             call    00404628
004967D9   33C0                   xor     eax, eax
004967DB   55                     push    ebp
004967DC   6838684900             push    $00496838

***** TRY
|
004967E1   64FF30                 push    dword ptr fs:[eax]
004967E4   648920                 mov     fs:[eax], esp
004967E7   8D55F4                 lea     edx, [ebp-$0C]
004967EA   8B45FC                 mov     eax, [ebp-$04]

* Reference to: SysUtils.UpperCase(AnsiString):AnsiString;
|
004967ED   E8721CF7FF             call    00408464
004967F2   8B45F4                 mov     eax, [ebp-$0C]
004967F5   50                     push    eax
004967F6   8D45F0                 lea     eax, [ebp-$10]
004967F9   50                     push    eax
004967FA   8B45FC                 mov     eax, [ebp-$04]

* Reference to: System.@LStrLen(String):Integer;
|
004967FD   E836DCF6FF             call    00404438
00496802   8BC8                   mov     ecx, eax
00496804   BA01000000             mov     edx, $00000001
00496809   8B45F8                 mov     eax, [ebp-$08]

* Reference to: System.@LStrCopy;
|
0049680C   E887DEF6FF             call    00404698
00496811   8B55F0                 mov     edx, [ebp-$10]
00496814   58                     pop     eax

* Reference to: System.@LStrCmp;
|
00496815   E86ADDF6FF             call    00404584
0049681A   0F94C3                 setz    bl
0049681D   33C0                   xor     eax, eax
0049681F   5A                     pop     edx
00496820   59                     pop     ecx
00496821   59                     pop     ecx
00496822   648910                 mov     fs:[eax], edx

****** FINALLY
|
00496825   683F684900             push    $0049683F
0049682A   8D45F0                 lea     eax, [ebp-$10]
0049682D   BA04000000             mov     edx, $00000004

* Reference to: System.@LStrArrayClr(void;void;Integer);
|
00496832   E865D9F6FF             call    0040419C
00496837   C3                     ret


* Reference to: System.@HandleFinally;
|
00496838   E93FD3F6FF             jmp     00403B7C
0049683D   EBEB                   jmp     0049682A

****** END
|
0049683F   8BC3                   mov     eax, ebx
00496841   5B                     pop     ebx
00496842   8BE5                   mov     esp, ebp
00496844   5D                     pop     ebp
00496845   C3                     ret

*)
end;

procedure Tform_about._PROC_00496AB5(Sender : TObject);
begin
(*
00496AB5   8BEC                   mov     ebp, esp
00496AB7   33C0                   xor     eax, eax
00496AB9   55                     push    ebp
00496ABA   68D96A4900             push    $00496AD9

***** TRY
|
00496ABF   64FF30                 push    dword ptr fs:[eax]
00496AC2   648920                 mov     fs:[eax], esp
00496AC5   FF05081E4A00           inc     dword ptr [$004A1E08]
00496ACB   33C0                   xor     eax, eax
00496ACD   5A                     pop     edx
00496ACE   59                     pop     ecx
00496ACF   59                     pop     ecx
00496AD0   648910                 mov     fs:[eax], edx

****** FINALLY
|
00496AD3   68E06A4900             push    $00496AE0
00496AD8   C3                     ret


* Reference to: System.@HandleFinally;
|
00496AD9   E99ED0F6FF             jmp     00403B7C
00496ADE   EBF8                   jmp     00496AD8

****** END
|
00496AE0   5D                     pop     ebp
00496AE1   C3                     ret

*)
end;

procedure Tform_about._PROC_00496AE4(Sender : TObject);
begin
(*
00496AE4   832D081E4A0001         sub     dword ptr [$004A1E08], +$01
00496AEB   C3                     ret

*)
end;

procedure Tform_about._PROC_00496AEC(Sender : TObject);
begin
(*
00496AEC   386B49                 cmp     [ebx+$49], ch
00496AEF   0000                   add     [eax], al

*)
end;

procedure Tform_about._PROC_00496BAA(Sender : TObject);
begin
(*
00496BAA   45                     inc     ebp
00496BAB   0034154700DCA5         add     [$A5DC0047+edx], dh
00496BB2   45                     inc     ebp
00496BB3   00F4                   add     ah, dh
00496BB5   E84500B0E9             call    E9F96BFF
00496BBA   45                     inc     ebp
00496BBB   0074E445               add     [esp+$45], dh
00496BBF   0094E94500CC04         add     [ecx+ebp*8+$4CC0045], dl
00496BC6   47                     inc     edi
00496BC7   00D8                   add     al, bl
00496BC9   1B4700                 sbb     eax, [edi+$00]
00496BCC   28BF45009C28           sub     [edi+$289C0045], bh
00496BD2   47                     inc     edi
00496BD3   00FC                   add     ah, bh
00496BD5   2B4700                 sub     eax, dword ptr [edi+$00]
00496BD8   B82A4700C0             mov     eax, $C000472A
00496BDD   BF4500C4BF             mov     edi, $BFC40045
00496BE2   45                     inc     ebp
00496BE3   00342D470024BE         add     [$BE240047+ebp], dh
00496BEA   45                     inc     ebp
00496BEB   00D4                   add     ah, dl
00496BED   EA45002834             jmp     $34280045
00496BF2   47                     inc     edi
00496BF3   0084FC450018E7         add     [esp+edi*8+$E7180045], al
00496BFA   45                     inc     ebp
00496BFB   003C49                 add     [ecx+ecx*2], bh
00496BFE   47                     inc     edi
00496BFF   00C0                   add     al, al
00496C01   FE4600                 inc     byte ptr [esi+$00]
00496C04   7001                   jo      00496C07
00496C06   47                     inc     edi
00496C07   001C3A                 add     [edx+edi], bl
00496C0A   47                     inc     edi
00496C0B   00580A                 add     [eax+$0A], bl
00496C0E   47                     inc     edi
00496C0F   00D4                   add     ah, dl
00496C11   0A4700                 or      al, byte ptr [edi+$00]
00496C14   1C4D                   sbb     al, $4D
00496C16   47                     inc     edi
00496C17   009007470020           add     [eax+$20004707], dl
00496C1D   48                     dec     eax
00496C1E   47                     inc     edi
00496C1F   0000                   add     [eax], al

*)
end;

procedure Tform_about._PROC_00496690(Sender : TObject);
begin
(*
00496690   53                     push    ebx
00496691   56                     push    esi
00496692   8BF2                   mov     esi, edx
00496694   8BD8                   mov     ebx, eax
00496696   8BD6                   mov     edx, esi

* Reference to control Tform_about.Label2 : TLabel
|
00496698   8B8310030000           mov     eax, [ebx+$0310]

* Reference to: Controls.TControl.GetText(TControl):TCaption;
|
0049669E   E8FD1BFCFF             call    004582A0
004966A3   5E                     pop     esi
004966A4   5B                     pop     ebx
004966A5   C3                     ret

*)
end;

procedure Tform_about._PROC_00496684(Sender : TObject);
begin
(*

* Reference to control Tform_about.Label3 : TLabel
|
00496684   8B8014030000           mov     eax, [eax+$0314]

* Reference to: Controls.TControl.SetText(TControl;TCaption);
|
0049668A   E8411CFCFF             call    004582D0
0049668F   C3                     ret

*)
end;

end.