unit unitform_login;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls
type
  Tform_login=class(TForm)
    panel_border: TPanel;
    Label1: TLabel;
    Label2: TLabel;
    lblPrompt: TLabel;
    lblShareware: TLabel;
    edit_username: TEdit;
    edit_serial: TEdit;
    btnOk: TRzBitBtn;
    btnRegL8R: TRzBitBtn;
    btnCancel: TRzBitBtn;
    procedure btnOkClick(Sender : TObject);
    procedure _PROC_004987C4(Sender : TObject);
    procedure _PROC_004987DC(Sender : TObject);
    procedure _PROC_004987F4(Sender : TObject);
    procedure _PROC_00498800(Sender : TObject);
    procedure _PROC_004988CB(Sender : TObject);
    procedure _PROC_00498A30(Sender : TObject);
    procedure _PROC_00498A9C(Sender : TObject);
    procedure _PROC_00498ACC(Sender : TObject);
    procedure _PROC_00498AD4(Sender : TObject);
    procedure _PROC_00498AD8(Sender : TObject);
    procedure _PROC_00498BD9(Sender : TObject);
    procedure _PROC_00498CD9(Sender : TObject);
    procedure _PROC_00498DE6(Sender : TObject);
    procedure _PROC_00498F08(Sender : TObject);
    procedure _PROC_00498F22(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end ;

var
  form_login: Tform_login;

{This file is generated by DeDe Ver 3.50.04 Copyright (c) 1999-2002 DaFixer}

implementation

{$R *.DFM}

procedure Tform_login.btnOkClick(Sender : TObject);
begin
(*
0049880C   55                     push    ebp
0049880D   8BEC                   mov     ebp, esp
0049880F   6A00                   push    $00
00498811   6A00                   push    $00
00498813   53                     push    ebx
00498814   8BD8                   mov     ebx, eax
00498816   33C0                   xor     eax, eax
00498818   55                     push    ebp

* Possible String Reference to: 'éÅ²öÿëë[YY]Ã'
|
00498819   68B2884900             push    $004988B2

***** TRY
|
0049881E   64FF30                 push    dword ptr fs:[eax]
00498821   648920                 mov     fs:[eax], esp
00498824   8BC3                   mov     eax, ebx
00498826   8B10                   mov     edx, [eax]

* Possible reference to virtual method Tform_login.OFFS_0104
|
00498828   FF9204010000           call    dword ptr [edx+$0104]

* Reference to pointer to GlobalVar_004A1D60
|
0049882E   8B15ACFF4900           mov     edx, [$0049FFAC]
00498834   8802                   mov     [edx], al

* Reference to pointer to GlobalVar_004A1D60
|
00498836   A1ACFF4900             mov     eax, dword ptr [$0049FFAC]
0049883B   803800                 cmp     byte ptr [eax], $00
0049883E   7519                   jnz     00498859
00498840   6A00                   push    $00
00498842   A100044A00             mov     eax, dword ptr [$004A0400]
00498847   8B00                   mov     eax, [eax]
00498849   668B0DC0884900         mov     cx, word ptr [$004988C0]
00498850   B201                   mov     dl, $01

|
00498852   E8EDA4F9FF             call    00432D44
00498857   EB3E                   jmp     00498897
00498859   8D55FC                 lea     edx, [ebp-$04]
0049885C   8BC3                   mov     eax, ebx
0049885E   8B08                   mov     ecx, [eax]

* Possible reference to virtual method Tform_login.OFFS_00F8
|
00498860   FF91F8000000           call    dword ptr [ecx+$00F8]
00498866   8B55FC                 mov     edx, [ebp-$04]

* Reference to pointer to GlobalVar_004A1D64
|
00498869   A1D4004A00             mov     eax, dword ptr [$004A00D4]

* Reference to: System.@LStrAsg(void;void;void;void);
|
0049886E   E859B9F6FF             call    004041CC
00498873   8D55F8                 lea     edx, [ebp-$08]
00498876   8BC3                   mov     eax, ebx
00498878   8B08                   mov     ecx, [eax]

* Possible reference to virtual method Tform_login.OFFS_00F4
|
0049887A   FF91F4000000           call    dword ptr [ecx+$00F4]
00498880   8B55F8                 mov     edx, [ebp-$08]

* Reference to pointer to GlobalVar_004A1D68
|
00498883   A11C034A00             mov     eax, dword ptr [$004A031C]

* Reference to: System.@LStrAsg(void;void;void;void);
|
00498888   E83FB9F6FF             call    004041CC

* Reference to field Tform_login.ModalResult : TModalResult
|
0049888D   C7834C02000001000000   mov     dword ptr [ebx+$024C], $00000001
00498897   33C0                   xor     eax, eax
00498899   5A                     pop     edx
0049889A   59                     pop     ecx
0049889B   59                     pop     ecx
0049889C   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '[YY]Ã'
|
0049889F   68B9884900             push    $004988B9
004988A4   8D45F8                 lea     eax, [ebp-$08]
004988A7   BA02000000             mov     edx, $00000002

* Reference to: System.@LStrArrayClr(void;void;Integer);
|
004988AC   E8EBB8F6FF             call    0040419C
004988B1   C3                     ret


* Reference to: System.@HandleFinally;
|
004988B2   E9C5B2F6FF             jmp     00403B7C
004988B7   EBEB                   jmp     004988A4

****** END
|
004988B9   5B                     pop     ebx
004988BA   59                     pop     ecx
004988BB   59                     pop     ecx
004988BC   5D                     pop     ebp
004988BD   C3                     ret

*)
end;

procedure Tform_login._PROC_004987C4(Sender : TObject);
begin
(*
004987C4   53                     push    ebx
004987C5   56                     push    esi
004987C6   8BF2                   mov     esi, edx
004987C8   8BD8                   mov     ebx, eax
004987CA   8BD6                   mov     edx, esi

* Reference to control Tform_login.edit_serial : TEdit
|
004987CC   8B8310030000           mov     eax, [ebx+$0310]

* Reference to: Controls.TControl.GetText(TControl):TCaption;
|
004987D2   E8C9FAFBFF             call    004582A0
004987D7   5E                     pop     esi
004987D8   5B                     pop     ebx
004987D9   C3                     ret

*)
end;

procedure Tform_login._PROC_004987DC(Sender : TObject);
begin
(*
004987DC   53                     push    ebx
004987DD   56                     push    esi
004987DE   8BF2                   mov     esi, edx
004987E0   8BD8                   mov     ebx, eax
004987E2   8BD6                   mov     edx, esi

* Reference to control Tform_login.edit_username : TEdit
|
004987E4   8B830C030000           mov     eax, [ebx+$030C]

* Reference to: Controls.TControl.GetText(TControl):TCaption;
|
004987EA   E8B1FAFBFF             call    004582A0
004987EF   5E                     pop     esi
004987F0   5B                     pop     ebx
004987F1   C3                     ret

*)
end;

procedure Tform_login._PROC_004987F4(Sender : TObject);
begin
(*

* Reference to control Tform_login.edit_serial : TEdit
|
004987F4   8B8010030000           mov     eax, [eax+$0310]

* Reference to: Controls.TControl.SetText(TControl;TCaption);
|
004987FA   E8D1FAFBFF             call    004582D0
004987FF   C3                     ret

*)
end;

procedure Tform_login._PROC_00498800(Sender : TObject);
begin
(*

* Reference to control Tform_login.edit_username : TEdit
|
00498800   8B800C030000           mov     eax, [eax+$030C]

* Reference to: Controls.TControl.SetText(TControl;TCaption);
|
00498806   E8C5FAFBFF             call    004582D0
0049880B   C3                     ret

*)
end;

procedure Tform_login._PROC_004988CB(Sender : TObject);
begin
(*
004988CB   C4F0                   les     esi, ax

* Reference to: System.@ClassCreate(TClass;Boolean):TObject;
|
004988CD   E87AAEF6FF             call    0040374C
004988D2   8BDA                   mov     ebx, edx
004988D4   8BF0                   mov     esi, eax
004988D6   33D2                   xor     edx, edx
004988D8   8BC6                   mov     eax, esi

* Reference to: Forms.TCustomForm.Create(TCustomForm;boolean;TComponent);
|
004988DA   E8ED7CFDFF             call    004705CC
004988DF   8B15B8004A00           mov     edx, [$004A00B8]
004988E5   8B12                   mov     edx, [edx]

* Reference to control Tform_login.lblPrompt : TLabel
|
004988E7   8B8604030000           mov     eax, [esi+$0304]

* Reference to: Controls.TControl.SetText(TControl;TCaption);
|
004988ED   E8DEF9FBFF             call    004582D0
004988F2   8B15B8024A00           mov     edx, [$004A02B8]
004988F8   8B12                   mov     edx, [edx]

* Reference to control Tform_login.Label1 : TLabel
|
004988FA   8B86FC020000           mov     eax, [esi+$02FC]

* Reference to: Controls.TControl.SetText(TControl;TCaption);
|
00498900   E8CBF9FBFF             call    004582D0
00498905   8B1544004A00           mov     edx, [$004A0044]
0049890B   8B12                   mov     edx, [edx]

* Reference to control Tform_login.Label2 : TLabel
|
0049890D   8B8600030000           mov     eax, [esi+$0300]

* Reference to: Controls.TControl.SetText(TControl;TCaption);
|
00498913   E8B8F9FBFF             call    004582D0
00498918   8B15F8024A00           mov     edx, [$004A02F8]
0049891E   8B12                   mov     edx, [edx]

* Reference to control Tform_login.btnOk : TRzBitBtn
|
00498920   8B8614030000           mov     eax, [esi+$0314]

* Reference to: Controls.TControl.SetText(TControl;TCaption);
|
00498926   E8A5F9FBFF             call    004582D0
0049892B   8B15FC014A00           mov     edx, [$004A01FC]
00498931   8B12                   mov     edx, [edx]

* Reference to control Tform_login.btnCancel : TRzBitBtn
|
00498933   8B861C030000           mov     eax, [esi+$031C]

* Reference to: Controls.TControl.SetText(TControl;TCaption);
|
00498939   E892F9FBFF             call    004582D0
0049893E   8B1570034A00           mov     edx, [$004A0370]
00498944   8B12                   mov     edx, [edx]

* Reference to control Tform_login.btnRegL8R : TRzBitBtn
|
00498946   8B8618030000           mov     eax, [esi+$0318]

* Reference to: Controls.TControl.SetText(TControl;TCaption);
|
0049894C   E87FF9FBFF             call    004582D0

* Reference to control Tform_login.btnRegL8R : TRzBitBtn
|
00498951   8B8618030000           mov     eax, [esi+$0318]
00498957   B201                   mov     dl, $01
00498959   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TRzBitBtn.OFFS_0150
|
0049895B   FF9150010000           call    dword ptr [ecx+$0150]

* Reference to pointer to GlobalVar_004A1E34
|
00498961   A158034A00             mov     eax, dword ptr [$004A0358]
00498966   833800                 cmp     dword ptr [eax], +$00
00498969   7F0E                   jnle    00498979

* Reference to pointer to GlobalVar_004A1E38
|
0049896B   A1C0004A00             mov     eax, dword ptr [$004A00C0]
00498970   833800                 cmp     dword ptr [eax], +$00
00498973   7F04                   jnle    00498979
00498975   33D2                   xor     edx, edx
00498977   EB02                   jmp     0049897B
00498979   B201                   mov     dl, $01

* Reference to control Tform_login.btnRegL8R : TRzBitBtn
|
0049897B   8B8618030000           mov     eax, [esi+$0318]

* Reference to: Controls.TControl.SetVisible(TControl;Boolean);
|
00498981   E83AF8FBFF             call    004581C0

* Reference to pointer to GlobalVar_004A1E3C
|
00498986   A17C044A00             mov     eax, dword ptr [$004A047C]
0049898B   833800                 cmp     dword ptr [eax], +$00
0049898E   7E2F                   jle     004989BF

* Reference to: SysUtils.Now:TDateTime;
|
00498990   E88B1BF7FF             call    0040A520

* Reference to: System.@TRUNC;
|
00498995   E80EA2F6FF             call    00402BA8
0049899A   52                     push    edx
0049899B   50                     push    eax

* Reference to pointer to GlobalVar_004A1E3C
|
0049899C   A17C044A00             mov     eax, dword ptr [$004A047C]
004989A1   8B00                   mov     eax, [eax]

* Reference to pointer to GlobalVar_004A1E34
|
004989A3   8B1558034A00           mov     edx, [$004A0358]
004989A9   0302                   add     eax, [edx]
004989AB   99                     cdq
004989AC   3B542404               cmp     edx, [esp+$04]
004989B0   7509                   jnz     004989BB
004989B2   3B0424                 cmp     eax, [esp]
004989B5   5A                     pop     edx
004989B6   58                     pop     eax
004989B7   7221                   jb      004989DA
004989B9   EB04                   jmp     004989BF
004989BB   5A                     pop     edx
004989BC   58                     pop     eax
004989BD   7C1B                   jl      004989DA

* Reference to pointer to GlobalVar_004A1E38
|
004989BF   A1C0004A00             mov     eax, dword ptr [$004A00C0]
004989C4   833800                 cmp     dword ptr [eax], +$00
004989C7   7E15                   jle     004989DE

* Reference to pointer to GlobalVar_004A1E40
|
004989C9   A108024A00             mov     eax, dword ptr [$004A0208]
004989CE   8B00                   mov     eax, [eax]

* Reference to pointer to GlobalVar_004A1E38
|
004989D0   8B15C0004A00           mov     edx, [$004A00C0]
004989D6   3B02                   cmp     eax, [edx]
004989D8   7C04                   jl      004989DE
004989DA   33D2                   xor     edx, edx
004989DC   EB02                   jmp     004989E0
004989DE   B201                   mov     dl, $01

* Reference to control Tform_login.btnRegL8R : TRzBitBtn
|
004989E0   8B8618030000           mov     eax, [esi+$0318]
004989E6   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TRzBitBtn.OFFS_64
|
004989E8   FF5164                 call    dword ptr [ecx+$64]

* Reference to pointer to GlobalVar_004A1D70
|
004989EB   A104044A00             mov     eax, dword ptr [$004A0404]
004989F0   8B00                   mov     eax, [eax]

* Reference to: Graphics.StringToColor(AnsiString):TColor;
|
004989F2   E80DC9F8FF             call    00425304
004989F7   8BD0                   mov     edx, eax

* Reference to field Tform_login.Font : TFont
|
004989F9   8B4668                 mov     eax, [esi+$68]

* Reference to: Graphics.TFont.SetColor(TFont;TColor);
|
004989FC   E8D7CDF8FF             call    004257D8

* Reference to pointer to GlobalVar_004A1D6C
|
00498A01   A1B0FF4900             mov     eax, dword ptr [$0049FFB0]
00498A06   8B00                   mov     eax, [eax]

* Reference to: Graphics.StringToColor(AnsiString):TColor;
|
00498A08   E8F7C8F8FF             call    00425304
00498A0D   8BD0                   mov     edx, eax
00498A0F   8BC6                   mov     eax, esi

* Reference to: Controls.TControl.SetColor(TControl;TColor);
|
00498A11   E82AFAFBFF             call    00458440
00498A16   8BC6                   mov     eax, esi
00498A18   84DB                   test    bl, bl
00498A1A   740F                   jz      00498A2B

* Reference to: System.@AfterConstruction(TObject):TObject;
|
00498A1C   E883ADF6FF             call    004037A4
00498A21   648F0500000000         pop     dword ptr fs:[$00000000]
00498A28   83C40C                 add     esp, +$0C
00498A2B   8BC6                   mov     eax, esi
00498A2D   5E                     pop     esi
00498A2E   5B                     pop     ebx
00498A2F   C3                     ret

*)
end;

procedure Tform_login._PROC_00498A30(Sender : TObject);
begin
(*
00498A30   53                     push    ebx
00498A31   33DB                   xor     ebx, ebx
00498A33   80FA02                 cmp     dl, $02
00498A36   7504                   jnz     00498A3C
00498A38   B301                   mov     bl, $01
00498A3A   EB5B                   jmp     00498A97
00498A3C   80FA01                 cmp     dl, $01
00498A3F   7556                   jnz     00498A97

* Reference to pointer to GlobalVar_004A1E3C
|
00498A41   A17C044A00             mov     eax, dword ptr [$004A047C]
00498A46   833800                 cmp     dword ptr [eax], +$00
00498A49   7E2F                   jle     00498A7A

* Reference to: SysUtils.Now:TDateTime;
|
00498A4B   E8D01AF7FF             call    0040A520

* Reference to: System.@TRUNC;
|
00498A50   E853A1F6FF             call    00402BA8
00498A55   52                     push    edx
00498A56   50                     push    eax

* Reference to pointer to GlobalVar_004A1E3C
|
00498A57   A17C044A00             mov     eax, dword ptr [$004A047C]
00498A5C   8B00                   mov     eax, [eax]

* Reference to pointer to GlobalVar_004A1E34
|
00498A5E   8B1558034A00           mov     edx, [$004A0358]
00498A64   0302                   add     eax, [edx]
00498A66   99                     cdq
00498A67   3B542404               cmp     edx, [esp+$04]
00498A6B   7509                   jnz     00498A76
00498A6D   3B0424                 cmp     eax, [esp]
00498A70   5A                     pop     edx
00498A71   58                     pop     eax
00498A72   7221                   jb      00498A95
00498A74   EB04                   jmp     00498A7A
00498A76   5A                     pop     edx
00498A77   58                     pop     eax
00498A78   7C1B                   jl      00498A95

* Reference to pointer to GlobalVar_004A1E38
|
00498A7A   A1C0004A00             mov     eax, dword ptr [$004A00C0]
00498A7F   833800                 cmp     dword ptr [eax], +$00
00498A82   7E13                   jle     00498A97

* Reference to pointer to GlobalVar_004A1E40
|
00498A84   A108024A00             mov     eax, dword ptr [$004A0208]
00498A89   8B00                   mov     eax, [eax]

* Reference to pointer to GlobalVar_004A1E38
|
00498A8B   8B15C0004A00           mov     edx, [$004A00C0]
00498A91   3B02                   cmp     eax, [edx]
00498A93   7C02                   jl      00498A97
00498A95   B301                   mov     bl, $01
00498A97   8BC3                   mov     eax, ebx
00498A99   5B                     pop     ebx
00498A9A   C3                     ret

*)
end;

procedure Tform_login._PROC_00498A9C(Sender : TObject);
begin
(*
00498A9C   55                     push    ebp
00498A9D   8BEC                   mov     ebp, esp
00498A9F   33C0                   xor     eax, eax
00498AA1   55                     push    ebp
00498AA2   68C18A4900             push    $00498AC1

***** TRY
|
00498AA7   64FF30                 push    dword ptr fs:[eax]
00498AAA   648920                 mov     fs:[eax], esp
00498AAD   FF05241E4A00           inc     dword ptr [$004A1E24]
00498AB3   33C0                   xor     eax, eax
00498AB5   5A                     pop     edx
00498AB6   59                     pop     ecx
00498AB7   59                     pop     ecx
00498AB8   648910                 mov     fs:[eax], edx

****** FINALLY
|
00498ABB   68C88A4900             push    $00498AC8
00498AC0   C3                     ret


* Reference to: System.@HandleFinally;
|
00498AC1   E9B6B0F6FF             jmp     00403B7C
00498AC6   EBF8                   jmp     00498AC0

****** END
|
00498AC8   5D                     pop     ebp
00498AC9   C3                     ret

*)
end;

procedure Tform_login._PROC_00498ACC(Sender : TObject);
begin
(*
00498ACC   832D241E4A0001         sub     dword ptr [$004A1E24], +$01
00498AD3   C3                     ret

*)
end;

procedure Tform_login._PROC_00498AD4(Sender : TObject);
begin
(*
00498AD4   C3                     ret

*)
end;

procedure Tform_login._PROC_00498AD8(Sender : TObject);
begin
(*
00498AD8   55                     push    ebp
00498AD9   8BEC                   mov     ebp, esp
00498ADB   6A00                   push    $00
00498ADD   6A00                   push    $00
00498ADF   6A00                   push    $00
00498AE1   53                     push    ebx
00498AE2   56                     push    esi
00498AE3   8BF2                   mov     esi, edx
00498AE5   8BD8                   mov     ebx, eax
00498AE7   33C0                   xor     eax, eax
00498AE9   55                     push    ebp
00498AEA   68B38B4900             push    $00498BB3

***** TRY
|
00498AEF   64FF30                 push    dword ptr fs:[eax]
00498AF2   648920                 mov     fs:[eax], esp
00498AF5   B201                   mov     dl, $01

* Reference to class TRegistry
|
00498AF7   A1185F4300             mov     eax, dword ptr [$00435F18]

* Reference to: Registry.TRegistry.Create(TRegistry;boolean);overload;
|
00498AFC   E817D5F9FF             call    00436018
00498B01   8945FC                 mov     [ebp-$04], eax
00498B04   33C0                   xor     eax, eax
00498B06   55                     push    ebp
00498B07   68918B4900             push    $00498B91

***** TRY
|
00498B0C   64FF30                 push    dword ptr fs:[eax]
00498B0F   648920                 mov     fs:[eax], esp
00498B12   BA01000080             mov     edx, $80000001
00498B17   8B45FC                 mov     eax, [ebp-$04]

* Reference to: Registry.TRegistry.SetRootKey(TRegistry;HKEY);
|
00498B1A   E899D5F9FF             call    004360B8
00498B1F   8D55F8                 lea     edx, [ebp-$08]

* Reference to pointer to GlobalVar_004A1DE4
|
00498B22   A194FF4900             mov     eax, dword ptr [$0049FF94]
00498B27   8B00                   mov     eax, [eax]

* Reference to : TRzBitBtn._PROC_0048F280()
|
00498B29   E85267FFFF             call    0048F280
00498B2E   8D45F8                 lea     eax, [ebp-$08]
00498B31   50                     push    eax
00498B32   8D4DF4                 lea     ecx, [ebp-$0C]

* Reference to pointer to GlobalVar_004A1D54
|
00498B35   A124FF4900             mov     eax, dword ptr [$0049FF24]
00498B3A   8B00                   mov     eax, [eax]
00498B3C   33D2                   xor     edx, edx

* Reference to: SysUtils.IntToHex(Integer;Integer):AnsiString;overload;
|
00498B3E   E8EDFEF6FF             call    00408A30
00498B43   8B55F4                 mov     edx, [ebp-$0C]
00498B46   58                     pop     eax

* Reference to: System.@LStrCat;
|
00498B47   E8F4B8F6FF             call    00404440
00498B4C   8B55F8                 mov     edx, [ebp-$08]
00498B4F   33C9                   xor     ecx, ecx
00498B51   8B45FC                 mov     eax, [ebp-$04]

* Reference to: Registry.TRegistry.OpenKey(TRegistry;AnsiString;Boolean):Boolean;
|
00498B54   E8C3D5F9FF             call    0043611C
00498B59   84C0                   test    al, al
00498B5B   741E                   jz      00498B7B

* Possible String Reference to: 'SD'
|
00498B5D   BAC88B4900             mov     edx, $00498BC8
00498B62   8B45FC                 mov     eax, [ebp-$04]

* Reference to: Registry.TRegistry.ReadInteger(TRegistry;AnsiString):Integer;
|
00498B65   E826D8F9FF             call    00436390
00498B6A   8903                   mov     [ebx], eax

* Possible String Reference to: 'SO'
|
00498B6C   BAD48B4900             mov     edx, $00498BD4
00498B71   8B45FC                 mov     eax, [ebp-$04]

* Reference to: Registry.TRegistry.ReadInteger(TRegistry;AnsiString):Integer;
|
00498B74   E817D8F9FF             call    00436390
00498B79   8906                   mov     [esi], eax
00498B7B   33C0                   xor     eax, eax
00498B7D   5A                     pop     edx
00498B7E   59                     pop     ecx
00498B7F   59                     pop     ecx
00498B80   648910                 mov     fs:[eax], edx

****** FINALLY
|
00498B83   68988B4900             push    $00498B98
00498B88   8B45FC                 mov     eax, [ebp-$04]

* Reference to: System.TObject.Free(TObject);
|
00498B8B   E858A8F6FF             call    004033E8
00498B90   C3                     ret


* Reference to: System.@HandleFinally;
|
00498B91   E9E6AFF6FF             jmp     00403B7C
00498B96   EBF0                   jmp     00498B88

****** END
|
00498B98   33C0                   xor     eax, eax
00498B9A   5A                     pop     edx
00498B9B   59                     pop     ecx
00498B9C   59                     pop     ecx
00498B9D   648910                 mov     fs:[eax], edx

****** FINALLY
|
00498BA0   68BA8B4900             push    $00498BBA
00498BA5   8D45F4                 lea     eax, [ebp-$0C]
00498BA8   BA02000000             mov     edx, $00000002

* Reference to: System.@LStrArrayClr(void;void;Integer);
|
00498BAD   E8EAB5F6FF             call    0040419C
00498BB2   C3                     ret


* Reference to: System.@HandleFinally;
|
00498BB3   E9C4AFF6FF             jmp     00403B7C
00498BB8   EBEB                   jmp     00498BA5

****** END
|
00498BBA   5E                     pop     esi
00498BBB   5B                     pop     ebx
00498BBC   8BE5                   mov     esp, ebp
00498BBE   5D                     pop     ebp
00498BBF   C3                     ret

*)
end;

procedure Tform_login._PROC_00498BD9(Sender : TObject);
begin
(*
00498BD9   8BEC                   mov     ebp, esp
00498BDB   6A00                   push    $00
00498BDD   6A00                   push    $00
00498BDF   6A00                   push    $00
00498BE1   53                     push    ebx
00498BE2   56                     push    esi
00498BE3   8BF2                   mov     esi, edx
00498BE5   8BD8                   mov     ebx, eax
00498BE7   33C0                   xor     eax, eax
00498BE9   55                     push    ebp
00498BEA   68B38C4900             push    $00498CB3

***** TRY
|
00498BEF   64FF30                 push    dword ptr fs:[eax]
00498BF2   648920                 mov     fs:[eax], esp
00498BF5   B201                   mov     dl, $01

* Reference to class TRegistry
|
00498BF7   A1185F4300             mov     eax, dword ptr [$00435F18]

* Reference to: Registry.TRegistry.Create(TRegistry;boolean);overload;
|
00498BFC   E817D4F9FF             call    00436018
00498C01   8945FC                 mov     [ebp-$04], eax
00498C04   33C0                   xor     eax, eax
00498C06   55                     push    ebp
00498C07   68918C4900             push    $00498C91

***** TRY
|
00498C0C   64FF30                 push    dword ptr fs:[eax]
00498C0F   648920                 mov     fs:[eax], esp
00498C12   BA01000080             mov     edx, $80000001
00498C17   8B45FC                 mov     eax, [ebp-$04]

* Reference to: Registry.TRegistry.SetRootKey(TRegistry;HKEY);
|
00498C1A   E899D4F9FF             call    004360B8
00498C1F   8D55F8                 lea     edx, [ebp-$08]

* Reference to pointer to GlobalVar_004A1DE4
|
00498C22   A194FF4900             mov     eax, dword ptr [$0049FF94]
00498C27   8B00                   mov     eax, [eax]

* Reference to : TRzBitBtn._PROC_0048F280()
|
00498C29   E85266FFFF             call    0048F280
00498C2E   8D45F8                 lea     eax, [ebp-$08]
00498C31   50                     push    eax
00498C32   8D4DF4                 lea     ecx, [ebp-$0C]

* Reference to pointer to GlobalVar_004A1D54
|
00498C35   A124FF4900             mov     eax, dword ptr [$0049FF24]
00498C3A   8B00                   mov     eax, [eax]
00498C3C   33D2                   xor     edx, edx

* Reference to: SysUtils.IntToHex(Integer;Integer):AnsiString;overload;
|
00498C3E   E8EDFDF6FF             call    00408A30
00498C43   8B55F4                 mov     edx, [ebp-$0C]
00498C46   58                     pop     eax

* Reference to: System.@LStrCat;
|
00498C47   E8F4B7F6FF             call    00404440
00498C4C   8B55F8                 mov     edx, [ebp-$08]
00498C4F   B101                   mov     cl, $01
00498C51   8B45FC                 mov     eax, [ebp-$04]

* Reference to: Registry.TRegistry.OpenKey(TRegistry;AnsiString;Boolean):Boolean;
|
00498C54   E8C3D4F9FF             call    0043611C
00498C59   84C0                   test    al, al
00498C5B   741E                   jz      00498C7B
00498C5D   8BCB                   mov     ecx, ebx

* Possible String Reference to: 'SD'
|
00498C5F   BAC88C4900             mov     edx, $00498CC8
00498C64   8B45FC                 mov     eax, [ebp-$04]

* Reference to: Registry.TRegistry.WriteInteger(TRegistry;AnsiString;Integer);
|
00498C67   E810D7F9FF             call    0043637C
00498C6C   8BCE                   mov     ecx, esi

* Possible String Reference to: 'SO'
|
00498C6E   BAD48C4900             mov     edx, $00498CD4
00498C73   8B45FC                 mov     eax, [ebp-$04]

* Reference to: Registry.TRegistry.WriteInteger(TRegistry;AnsiString;Integer);
|
00498C76   E801D7F9FF             call    0043637C
00498C7B   33C0                   xor     eax, eax
00498C7D   5A                     pop     edx
00498C7E   59                     pop     ecx
00498C7F   59                     pop     ecx
00498C80   648910                 mov     fs:[eax], edx

****** FINALLY
|
00498C83   68988C4900             push    $00498C98
00498C88   8B45FC                 mov     eax, [ebp-$04]

* Reference to: System.TObject.Free(TObject);
|
00498C8B   E858A7F6FF             call    004033E8
00498C90   C3                     ret


* Reference to: System.@HandleFinally;
|
00498C91   E9E6AEF6FF             jmp     00403B7C
00498C96   EBF0                   jmp     00498C88

****** END
|
00498C98   33C0                   xor     eax, eax
00498C9A   5A                     pop     edx
00498C9B   59                     pop     ecx
00498C9C   59                     pop     ecx
00498C9D   648910                 mov     fs:[eax], edx

****** FINALLY
|
00498CA0   68BA8C4900             push    $00498CBA
00498CA5   8D45F4                 lea     eax, [ebp-$0C]
00498CA8   BA02000000             mov     edx, $00000002

* Reference to: System.@LStrArrayClr(void;void;Integer);
|
00498CAD   E8EAB4F6FF             call    0040419C
00498CB2   C3                     ret


* Reference to: System.@HandleFinally;
|
00498CB3   E9C4AEF6FF             jmp     00403B7C
00498CB8   EBEB                   jmp     00498CA5

****** END
|
00498CBA   5E                     pop     esi
00498CBB   5B                     pop     ebx
00498CBC   8BE5                   mov     esp, ebp
00498CBE   5D                     pop     ebp
00498CBF   C3                     ret

*)
end;

procedure Tform_login._PROC_00498CD9(Sender : TObject);
begin
(*
00498CD9   8BEC                   mov     ebp, esp
00498CDB   33C9                   xor     ecx, ecx
00498CDD   51                     push    ecx
00498CDE   51                     push    ecx
00498CDF   51                     push    ecx
00498CE0   51                     push    ecx
00498CE1   51                     push    ecx
00498CE2   53                     push    ebx
00498CE3   56                     push    esi
00498CE4   8BF2                   mov     esi, edx
00498CE6   8BD8                   mov     ebx, eax
00498CE8   33C0                   xor     eax, eax
00498CEA   55                     push    ebp

* Possible String Reference to: 'é­­öÿëë^[‹å]Ã'
|
00498CEB   68CA8D4900             push    $00498DCA

***** TRY
|
00498CF0   64FF30                 push    dword ptr fs:[eax]
00498CF3   648920                 mov     fs:[eax], esp
00498CF6   B201                   mov     dl, $01

* Reference to class TRegistry
|
00498CF8   A1185F4300             mov     eax, dword ptr [$00435F18]

* Reference to: Registry.TRegistry.Create(TRegistry;boolean);overload;
|
00498CFD   E816D3F9FF             call    00436018
00498D02   8945FC                 mov     [ebp-$04], eax
00498D05   33C0                   xor     eax, eax
00498D07   55                     push    ebp
00498D08   68A88D4900             push    $00498DA8

***** TRY
|
00498D0D   64FF30                 push    dword ptr fs:[eax]
00498D10   648920                 mov     fs:[eax], esp
00498D13   BA01000080             mov     edx, $80000001
00498D18   8B45FC                 mov     eax, [ebp-$04]

* Reference to: Registry.TRegistry.SetRootKey(TRegistry;HKEY);
|
00498D1B   E898D3F9FF             call    004360B8
00498D20   8D55F8                 lea     edx, [ebp-$08]

* Reference to pointer to GlobalVar_004A1DE4
|
00498D23   A194FF4900             mov     eax, dword ptr [$0049FF94]
00498D28   8B00                   mov     eax, [eax]

* Reference to : TRzBitBtn._PROC_0048F280()
|
00498D2A   E85165FFFF             call    0048F280
00498D2F   8D45F8                 lea     eax, [ebp-$08]
00498D32   50                     push    eax
00498D33   8D4DF4                 lea     ecx, [ebp-$0C]

* Reference to pointer to GlobalVar_004A1D54
|
00498D36   A124FF4900             mov     eax, dword ptr [$0049FF24]
00498D3B   8B00                   mov     eax, [eax]
00498D3D   33D2                   xor     edx, edx

* Reference to: SysUtils.IntToHex(Integer;Integer):AnsiString;overload;
|
00498D3F   E8ECFCF6FF             call    00408A30
00498D44   8B55F4                 mov     edx, [ebp-$0C]
00498D47   58                     pop     eax

* Reference to: System.@LStrCat;
|
00498D48   E8F3B6F6FF             call    00404440
00498D4D   8B55F8                 mov     edx, [ebp-$08]
00498D50   33C9                   xor     ecx, ecx
00498D52   8B45FC                 mov     eax, [ebp-$04]

* Reference to: Registry.TRegistry.OpenKey(TRegistry;AnsiString;Boolean):Boolean;
|
00498D55   E8C2D3F9FF             call    0043611C
00498D5A   84C0                   test    al, al
00498D5C   7434                   jz      00498D92
00498D5E   8D4DF0                 lea     ecx, [ebp-$10]

* Possible String Reference to: 'LoginUser'
|
00498D61   BAE08D4900             mov     edx, $00498DE0
00498D66   8B45FC                 mov     eax, [ebp-$04]

* Reference to: Registry.TRegistry.ReadString(TRegistry;AnsiString):AnsiString;
|
00498D69   E896D5F9FF             call    00436304
00498D6E   8B55F0                 mov     edx, [ebp-$10]
00498D71   8BC3                   mov     eax, ebx

* Reference to: System.@LStrAsg(void;void;void;void);
|
00498D73   E854B4F6FF             call    004041CC
00498D78   8D4DEC                 lea     ecx, [ebp-$14]

* Possible String Reference to: 'LoginPassword'
|
00498D7B   BAF48D4900             mov     edx, $00498DF4
00498D80   8B45FC                 mov     eax, [ebp-$04]

* Reference to: Registry.TRegistry.ReadString(TRegistry;AnsiString):AnsiString;
|
00498D83   E87CD5F9FF             call    00436304
00498D88   8B55EC                 mov     edx, [ebp-$14]
00498D8B   8BC6                   mov     eax, esi

* Reference to: System.@LStrAsg(void;void;void;void);
|
00498D8D   E83AB4F6FF             call    004041CC
00498D92   33C0                   xor     eax, eax
00498D94   5A                     pop     edx
00498D95   59                     pop     ecx
00498D96   59                     pop     ecx
00498D97   648910                 mov     fs:[eax], edx

****** FINALLY
|
00498D9A   68AF8D4900             push    $00498DAF
00498D9F   8B45FC                 mov     eax, [ebp-$04]

* Reference to: System.TObject.Free(TObject);
|
00498DA2   E841A6F6FF             call    004033E8
00498DA7   C3                     ret


* Reference to: System.@HandleFinally;
|
00498DA8   E9CFADF6FF             jmp     00403B7C
00498DAD   EBF0                   jmp     00498D9F

****** END
|
00498DAF   33C0                   xor     eax, eax
00498DB1   5A                     pop     edx
00498DB2   59                     pop     ecx
00498DB3   59                     pop     ecx
00498DB4   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '^[‹å]Ã'
|
00498DB7   68D18D4900             push    $00498DD1
00498DBC   8D45EC                 lea     eax, [ebp-$14]
00498DBF   BA04000000             mov     edx, $00000004

* Reference to: System.@LStrArrayClr(void;void;Integer);
|
00498DC4   E8D3B3F6FF             call    0040419C
00498DC9   C3                     ret


* Reference to: System.@HandleFinally;
|
00498DCA   E9ADADF6FF             jmp     00403B7C
00498DCF   EBEB                   jmp     00498DBC

****** END
|
00498DD1   5E                     pop     esi
00498DD2   5B                     pop     ebx
00498DD3   8BE5                   mov     esp, ebp
00498DD5   5D                     pop     ebp
00498DD6   C3                     ret

*)
end;

procedure Tform_login._PROC_00498DE6(Sender : TObject);
begin
(*
00498DE6   7365                   jnb     00498E4D
00498DE8   7200                   jb      00498DEA
00498DEA   0000                   add     [eax], al

00498DEC   FFFF                   DB  $FF, $FF  //      
00498DEE   FFFF                   DB  $FF, $FF  //      
00498DF0   0D0000004C             or      eax, $4C000000
00498DF5   6F                     outsd
00498DF6   67696E5061737377       imul    ebp, [bp+$50], $77737361
00498DFE   6F                     outsd
00498DFF   7264                   jb      00498E65
00498E01   0000                   add     [eax], al

00498E03   00558B                 add     [ebp-$75], dl
00498E06   EC                     in      al, dx
00498E07   83C4EC                 add     esp, -$14
00498E0A   33C9                   xor     ecx, ecx
00498E0C   894DF0                 mov     [ebp-$10], ecx
00498E0F   894DEC                 mov     [ebp-$14], ecx
00498E12   8955F8                 mov     [ebp-$08], edx
00498E15   8945FC                 mov     [ebp-$04], eax
00498E18   8B45FC                 mov     eax, [ebp-$04]

* Reference to: System.@LStrAddRef(void;void):Pointer;
|
00498E1B   E808B8F6FF             call    00404628
00498E20   8B45F8                 mov     eax, [ebp-$08]

* Reference to: System.@LStrAddRef(void;void):Pointer;
|
00498E23   E800B8F6FF             call    00404628
00498E28   33C0                   xor     eax, eax
00498E2A   55                     push    ebp

* Possible String Reference to: 'éo¬öÿëÞ‹å]Ã'
|
00498E2B   68088F4900             push    $00498F08

***** TRY
|
00498E30   64FF30                 push    dword ptr fs:[eax]
00498E33   648920                 mov     fs:[eax], esp
00498E36   B201                   mov     dl, $01

* Reference to class TRegistry
|
00498E38   A1185F4300             mov     eax, dword ptr [$00435F18]

* Reference to: Registry.TRegistry.Create(TRegistry;boolean);overload;
|
00498E3D   E8D6D1F9FF             call    00436018
00498E42   8945F4                 mov     [ebp-$0C], eax
00498E45   33C0                   xor     eax, eax
00498E47   55                     push    ebp
00498E48   68D98E4900             push    $00498ED9

***** TRY
|
00498E4D   64FF30                 push    dword ptr fs:[eax]
00498E50   648920                 mov     fs:[eax], esp
00498E53   BA01000080             mov     edx, $80000001
00498E58   8B45F4                 mov     eax, [ebp-$0C]

* Reference to: Registry.TRegistry.SetRootKey(TRegistry;HKEY);
|
00498E5B   E858D2F9FF             call    004360B8
00498E60   8D55F0                 lea     edx, [ebp-$10]

* Reference to pointer to GlobalVar_004A1DE4
|
00498E63   A194FF4900             mov     eax, dword ptr [$0049FF94]
00498E68   8B00                   mov     eax, [eax]

* Reference to : TRzBitBtn._PROC_0048F280()
|
00498E6A   E81164FFFF             call    0048F280
00498E6F   8D45F0                 lea     eax, [ebp-$10]
00498E72   50                     push    eax
00498E73   8D4DEC                 lea     ecx, [ebp-$14]

* Reference to pointer to GlobalVar_004A1D54
|
00498E76   A124FF4900             mov     eax, dword ptr [$0049FF24]
00498E7B   8B00                   mov     eax, [eax]
00498E7D   33D2                   xor     edx, edx

* Reference to: SysUtils.IntToHex(Integer;Integer):AnsiString;overload;
|
00498E7F   E8ACFBF6FF             call    00408A30
00498E84   8B55EC                 mov     edx, [ebp-$14]
00498E87   58                     pop     eax

* Reference to: System.@LStrCat;
|
00498E88   E8B3B5F6FF             call    00404440
00498E8D   8B55F0                 mov     edx, [ebp-$10]
00498E90   B101                   mov     cl, $01
00498E92   8B45F4                 mov     eax, [ebp-$0C]

* Reference to: Registry.TRegistry.OpenKey(TRegistry;AnsiString;Boolean):Boolean;
|
00498E95   E882D2F9FF             call    0043611C
00498E9A   84C0                   test    al, al
00498E9C   7425                   jz      00498EC3

* Reference to : Tform_login._PROC_00498AD4()
|
00498E9E   E831FCFFFF             call    00498AD4
00498EA3   8B4DFC                 mov     ecx, [ebp-$04]

* Possible String Reference to: 'LoginUser'
|
00498EA6   BA1C8F4900             mov     edx, $00498F1C
00498EAB   8B45F4                 mov     eax, [ebp-$0C]

* Reference to: Registry.TRegistry.WriteString(TRegistry;AnsiString;AnsiString);
|
00498EAE   E825D4F9FF             call    004362D8
00498EB3   8B4DF8                 mov     ecx, [ebp-$08]

* Possible String Reference to: 'LoginPassword'
|
00498EB6   BA308F4900             mov     edx, $00498F30
00498EBB   8B45F4                 mov     eax, [ebp-$0C]

* Reference to: Registry.TRegistry.WriteString(TRegistry;AnsiString;AnsiString);
|
00498EBE   E815D4F9FF             call    004362D8
00498EC3   33C0                   xor     eax, eax
00498EC5   5A                     pop     edx
00498EC6   59                     pop     ecx
00498EC7   59                     pop     ecx
00498EC8   648910                 mov     fs:[eax], edx

****** FINALLY
|
00498ECB   68E08E4900             push    $00498EE0
00498ED0   8B45F4                 mov     eax, [ebp-$0C]

* Reference to: System.TObject.Free(TObject);
|
00498ED3   E810A5F6FF             call    004033E8
00498ED8   C3                     ret


* Reference to: System.@HandleFinally;
|
00498ED9   E99EACF6FF             jmp     00403B7C
00498EDE   EBF0                   jmp     00498ED0

****** END
|
00498EE0   33C0                   xor     eax, eax
00498EE2   5A                     pop     edx
00498EE3   59                     pop     ecx
00498EE4   59                     pop     ecx
00498EE5   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '‹å]Ã'
|
00498EE8   680F8F4900             push    $00498F0F
00498EED   8D45EC                 lea     eax, [ebp-$14]
00498EF0   BA02000000             mov     edx, $00000002

* Reference to: System.@LStrArrayClr(void;void;Integer);
|
00498EF5   E8A2B2F6FF             call    0040419C
00498EFA   8D45F8                 lea     eax, [ebp-$08]
00498EFD   BA02000000             mov     edx, $00000002

* Reference to: System.@LStrArrayClr(void;void;Integer);
|
00498F02   E895B2F6FF             call    0040419C
00498F07   C3                     ret

*)
end;

procedure Tform_login._PROC_00498F08(Sender : TObject);
begin
(*

* Reference to: System.@HandleFinally;
|
00498F08   E96FACF6FF             jmp     00403B7C

|
00498F0D   EBDE                   jmp     00498EED
00498F0F   8BE5                   mov     esp, ebp
00498F11   5D                     pop     ebp
00498F12   C3                     ret

*)
end;

procedure Tform_login._PROC_00498F22(Sender : TObject);
begin
(*
00498F22   7365                   jnb     00498F89
00498F24   7200                   jb      00498F26
00498F26   0000                   add     [eax], al

00498F28   FFFF                   DB  $FF, $FF  //      
00498F2A   FFFF                   DB  $FF, $FF  //      
00498F2C   0D0000004C             or      eax, $4C000000
00498F31   6F                     outsd
00498F32   67696E5061737377       imul    ebp, [bp+$50], $77737361
00498F3A   6F                     outsd
00498F3B   7264                   jb      00498FA1
00498F3D   0000                   add     [eax], al

00498F3F   00558B                 add     [ebp-$75], dl
00498F42   EC                     in      al, dx
00498F43   33C0                   xor     eax, eax
00498F45   55                     push    ebp
00498F46   68658F4900             push    $00498F65

***** TRY
|
00498F4B   64FF30                 push    dword ptr fs:[eax]
00498F4E   648920                 mov     fs:[eax], esp
00498F51   FF05281E4A00           inc     dword ptr [$004A1E28]
00498F57   33C0                   xor     eax, eax
00498F59   5A                     pop     edx
00498F5A   59                     pop     ecx
00498F5B   59                     pop     ecx
00498F5C   648910                 mov     fs:[eax], edx

****** FINALLY
|
00498F5F   686C8F4900             push    $00498F6C
00498F64   C3                     ret


* Reference to: System.@HandleFinally;
|
00498F65   E912ACF6FF             jmp     00403B7C
00498F6A   EBF8                   jmp     00498F64

****** END
|
00498F6C   5D                     pop     ebp
00498F6D   C3                     ret

00498F6E   8BC0                   mov     eax, eax
00498F70   832D281E4A0001         sub     dword ptr [$004A1E28], +$01
00498F77   C3                     ret

00498F78   C48F49000000           les     ecx, [edi+$0049]
00498F7E   0000                   add     [eax], al

00498F80   0000                   add     [eax], al

00498F82   0000                   add     [eax], al

00498F84   CC                     int     3
00498F85   90                     nop
00498F86   49                     dec     ecx
00498F87   00449149               add     [ecx+edx*4+$49], al
00498F8B   00DE                   add     dh, bl
00498F8D   90                     nop
00498F8E   49                     dec     ecx
00498F8F   00FA                   add     dl, bh
00498F91   90                     nop
00498F92   49                     dec     ecx
00498F93   0000                   add     [eax], al

00498F95   0000                   add     [eax], al

00498F97   0028                   add     [eax], ch
00498F99   91                     xchg    eax, ecx
00498F9A   49                     dec     ecx
00498F9B   0030                   add     [eax], dh
00498F9D   0300                   add     eax, [eax]
00498F9F   00E8                   add     al, ch
00498FA1   844900                 test    [ecx+$00], cl
00498FA4   98                     cwde 
00498FA5   2A4200                 sub     al, byte ptr [edx+$00]
00498FA8   58                     pop     eax
00498FA9   07                     pop     es
00498FAA   47                     inc     edi
00498FAB   000C09                 add     [ecx+ecx], cl
00498FAE   47                     inc     edi
00498FAF   00443640               add     [esi+esi+$40], al
00498FB3   00782D                 add     [eax+$2D], bh
00498FB6   47                     inc     edi
00498FB7   00803340009C           add     [eax+$9C004033], al
00498FBD   334000                 xor     eax, [eax+$00]
00498FC0   7409                   jz      00498FCB
00498FC2   47                     inc     edi
00498FC3   0094F54500E40E         add     [ebp+esi*8+$EE40045], dl
00498FCA   47                     inc     edi
00498FCB   00DC                   add     ah, bl
00498FCD   A4                     movsb
00498FCE   41                     inc     ecx
00498FCF   00340B                 add     [ebx+ecx], dh
00498FD2   47                     inc     edi
00498FD3   00700B                 add     [eax+$0B], dh
00498FD6   47                     inc     edi
00498FD7   007C0C47               add     [esp+ecx+$47], bh
00498FDB   0088804500B0           add     [eax+$B0004580], cl
00498FE1   2A4200                 sub     al, byte ptr [edx+$00]
00498FE4   F4                     hlt
00498FE5   1447                   adc     al, $47
00498FE7   009027420094           add     [eax+$94004227], dl
00498FED   50                     push    eax
00498FEE   47                     inc     edi
00498FEF   004092                 add     [eax-$6E], al
00498FF2   49                     dec     ecx
00498FF3   00A8F04500C4           add     [eax+$C40045F0], ch
00498FF9   F5                     cmc
00498FFA   45                     inc     ebp
00498FFB   0010                   add     [eax], dl
00498FFD   F5                     cmc
00498FFE   45                     inc     ebp
00498FFF   00BC75450068EB         add     [ebp+esi*2+$EB680045], bh
00499006   45                     inc     ebp
00499007   00D4                   add     ah, dl
00499009   114700                 adc     [edi+$00], eax
0049900C   68E8450004             push    $040045E8
00499011   7545                   jnz     00499058
00499013   0008                   add     [eax], cl
00499015   7545                   jnz     0049905C
00499017   00C8                   add     al, cl
00499019   124700                 adc     al, byte ptr [edi+$00]
0049901C   58                     pop     eax
0049901D   A5                     movsd
0049901E   45                     inc     ebp
0049901F   007080                 add     [eax-$80], dh
00499022   45                     inc     ebp
00499023   0080764500FC           add     [eax+$FC004576], al
00499029   814500BC144700         add     dword ptr [ebp+$00], $004714BC
00499030   8813                   mov     [ebx], dl
00499032   47                     inc     edi
00499033   003483                 add     [ebx+eax*4], dh
00499036   45                     inc     ebp
00499037   0034154700DCA5         add     [$A5DC0047+edx], dh
0049903E   45                     inc     ebp
0049903F   00F4                   add     ah, dh
00499041   E84500B0E9             call    E9F9908B
00499046   45                     inc     ebp
00499047   0074E445               add     [esp+$45], dh
0049904B   0094E94500CC04         add     [ecx+ebp*8+$4CC0045], dl
00499052   47                     inc     edi
00499053   00D8                   add     al, bl
00499055   1B4700                 sbb     eax, [edi+$00]
00499058   28BF45009C28           sub     [edi+$289C0045], bh
0049905E   47                     inc     edi
0049905F   00FC                   add     ah, bh
00499061   2B4700                 sub     eax, dword ptr [edi+$00]
00499064   B82A4700C0             mov     eax, $C000472A
00499069   BF4500C4BF             mov     edi, $BFC40045
0049906E   45                     inc     ebp
0049906F   00342D470024BE         add     [$BE240047+ebp], dh
00499076   45                     inc     ebp
00499077   00D4                   add     ah, dl
00499079   EA45002834             jmp     $34280045
0049907E   47                     inc     edi
0049907F   0084FC450018E7         add     [esp+edi*8+$E7180045], al
00499086   45                     inc     ebp
00499087   003C49                 add     [ecx+ecx*2], bh
0049908A   47                     inc     edi
0049908B   00C0                   add     al, al
0049908D   FE4600                 inc     byte ptr [esi+$00]
00499090   7001                   jo      00499093
00499092   47                     inc     edi
00499093   001C3A                 add     [edx+edi], bl
00499096   47                     inc     edi
00499097   00580A                 add     [eax+$0A], bl
0049909A   47                     inc     edi
0049909B   00D4                   add     ah, dl
0049909D   0A4700                 or      al, byte ptr [edi+$00]
004990A0   1C4D                   sbb     al, $4D
004990A2   47                     inc     edi
004990A3   009007470020           add     [eax+$20004707], dl
004990A9   48                     dec     eax
004990AA   47                     inc     edi
004990AB   0000                   add     [eax], al

*)
end;

end.